import { neon } from '@neondatabase/serverless';
import { Resend } from 'resend';

const sql = neon(process.env.DATABASE_URL || '');
const labels: Record<string, string> = { nova:'Nová objednávka',zpracovava_se:'Objednávka se zpracovává',zaplaceno:'Objednávka zaplacena',u_prepravce:'Objednávka je u přepravce',odeslano:'Objednávka odeslána',dokonceno:'Objednávka dokončena',zruseno:'Objednávka zrušena' };
function esc(v: any) { return String(v ?? '').replace(/[&<>\"']/g, (c: string) => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c] || c)); }
function formatMoney(v: any) { return Number(v ?? 0).toLocaleString('cs-CZ', { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }
function variableSymbol(order: any, id: string) { return String(order?.variableSymbol || order?.orderNumber || id || '').replace(/\D/g, ''); }
function paymentQrUrl(order: any, id: string) { const params = new URLSearchParams({ accountNumber:'963625003',bankCode:'5500',amount:Number(order?.totalPrice || 0).toFixed(2),currency:'CZK',vs:variableSymbol(order,id),message:String(order?.orderNumber || id || '').trim(),size:'220' }); return `https://api.paylibo.com/paylibo/generator/czech/image?${params.toString()}`; }
function shippingAmount(order: any, delivery: any) { const direct=[order?.shipping,delivery?.shipping,delivery?.price,delivery?.shippingPrice].map(Number).find(v=>Number.isFinite(v)); if(direct!==undefined)return direct; const method=String(delivery?.method||''); const carrier=String(delivery?.carrier||'').toUpperCase(); if(method==='personal_pickup')return 0; if(carrier==='UPS')return 356; if(carrier==='PENGUINBOX')return 59; if(carrier==='ZASILKOVNA'&&String(delivery?.country||'').toUpperCase()==='SK')return 0; const baseMap:any={BALIKOVNA:{pickup:52,address:88},DPD:{pickup:85,address:98},GLS:{pickup:52},WEDO:{pickup:57,address:92},PPL:{pickup:68},ZASILKOVNA:{pickup:72,address:99}}; const base=baseMap[carrier]?.[method==='address'?'address':'pickup']; return base===undefined?0:Number((base*1.105*1.21).toFixed(2)); }
function productsHtml(order: any) { const items=Array.isArray(order?.items)?order.items:[]; return items.map((item:any)=>{const qty=Number(item?.quantity||1);const unit=Number(item?.price||0);const line=unit*qty;return `<tr><td style="padding:10px;border-bottom:1px solid #eee"><strong>${esc(item?.title||'Produkt')}</strong></td><td style="padding:10px;border-bottom:1px solid #eee;text-align:center">${qty}×</td><td style="padding:10px;border-bottom:1px solid #eee;text-align:right;white-space:nowrap">${formatMoney(line)} Kč</td></tr>`;}).join('')||'<tr><td colspan="3" style="padding:10px;color:#777">Žádné produkty</td></tr>'; }
function pickupAddressOf(delivery: any) { const p=delivery?.pickupPoint; const direct=delivery?.pickupPointAddress||delivery?.pickupAddress||delivery?.pickupPointFullAddress||delivery?.pickupAddressFull; if(direct)return String(direct).trim(); if(p&&typeof p==='object')return String(p.formattedAddress||p.address||[p.street,p.zip,p.city].filter(Boolean).join(', ')||'').trim(); return ''; }
function pickupLabelOf(delivery: any) { const p=delivery?.pickupPoint; if(p&&typeof p==='object')return String(p.name||p.label||p.title||p.placeName||'').trim(); return String(p||delivery?.pickupPointName||'').trim(); }

export async function sendOrderStatusEmails(order: any, id: string, status: string) {
  if (!labels[status]) throw new Error('Chybí nebo je neplatný stav objednávky.');
  const apiKey=process.env.RESEND_API_KEY;
  if(!apiKey) throw new Error('Ve Vercelu chybí RESEND_API_KEY.');
  const to=String(order?.customer?.email||'').trim();
  const seller=String(process.env.ORDER_NOTIFY_EMAIL||'objednavky@luvia-decor.cz').trim();
  if(!to) throw new Error('Objednávka nemá e-mail zákazníka.');
  const resend=new Resend(apiKey); const label=labels[status]; const delivery=order?.delivery||{};
  const carrier=String(delivery?.carrier||order?.shippingCarrier||order?.carrier||'').trim()||'Doprava'; const vs=variableSymbol(order,id); const orderNo=String(order?.orderNumber||id); const shipping=shippingAmount(order,delivery); const total=Number(order?.totalPrice??0); const pickupAddress=pickupAddressOf(delivery); const pickupLabel=pickupLabelOf(delivery); const pickupDetails=[pickupLabel,pickupAddress].filter(Boolean).join(' · ');
  const deliveryText=delivery?.method==='personal_pickup'?'Osobní odběr – Kroměříž':delivery?.method==='box'?`Box – ${carrier}${pickupDetails?`: ${pickupDetails}`:''}`:delivery?.method==='pickup_point'?`Výdejní místo – ${carrier}${pickupDetails?`: ${pickupDetails}`:''}`:`Doručení na adresu – ${carrier}`;
  const html=`<div style="font-family:Arial,sans-serif;max-width:650px;margin:auto"><h1>LUVIA DECOR</h1><h2>${esc(label)}</h2><p>Dobrý den, ${esc(order?.customer?.fullName||'zákazníku')},</p><p>Stav Vaší objednávky <strong>${esc(orderNo)}</strong> byl změněn na <strong>${esc(label)}</strong>.</p><div style="margin:18px 0;padding:14px;background:#faf8f5;border-radius:10px;line-height:1.8;font-size:13px"><strong>Doprava:</strong> ${esc(carrier)}<br><strong>Způsob doručení:</strong> ${esc(deliveryText)}${pickupLabel?`<br><strong>Výdejní místo:</strong> ${esc(pickupLabel)}`:''}${pickupAddress?`<br><strong>Přesná adresa výdejního místa:</strong> ${esc(pickupAddress)}`:''}</div><table style="width:100%;border-collapse:collapse;margin:20px 0"><thead><tr><th style="padding:10px;text-align:left;border-bottom:1px solid #ddd">Produkty</th><th style="padding:10px;text-align:center;border-bottom:1px solid #ddd">Ks</th><th style="padding:10px;text-align:right;border-bottom:1px solid #ddd">Cena</th></tr></thead><tbody>${productsHtml(order)}<tr><td style="padding:10px;border-bottom:1px solid #eee"><strong>Doprava (${esc(carrier)})</strong></td><td style="padding:10px;border-bottom:1px solid #eee;text-align:center">1×</td><td style="padding:10px;border-bottom:1px solid #eee;text-align:right;white-space:nowrap"><strong>${formatMoney(shipping)} Kč</strong></td></tr><tr><td colspan="2" style="padding:14px 10px 10px;text-align:right"><strong>Celkem:</strong></td><td style="padding:14px 10px 10px;text-align:right;white-space:nowrap"><strong>${formatMoney(total)} Kč</strong></td></tr></tbody></table><div style="margin-top:24px;padding:20px;background:#faf8f5;border:1px solid #eee5dc;border-radius:14px"><strong>Platba bankovním převodem</strong><div style="font-size:13px;line-height:1.8;margin-top:10px">Číslo účtu (ČR): <strong>963625003/5500</strong><br>IBAN (zahraniční platby): <strong>CZ96 5500 0000 0009 6362 5003</strong><br>SWIFT/BIC: <strong>RZBCCZPP</strong><br>Variabilní symbol: <strong>${esc(vs)}</strong><br>Částka: <strong>${formatMoney(total)} Kč</strong><br>Poznámka pro příjemce: <strong>${esc(orderNo)}</strong></div><div style="text-align:center;margin-top:16px"><img src="${paymentQrUrl(order,id)}" width="220" height="220" alt="QR platba" style="display:inline-block;border:1px solid #e6ded5;border-radius:8px"></div></div><p>V případě dotazů nám odpovězte na tento e-mail.</p></div>`;
  const results=await Promise.allSettled([resend.emails.send({from:'Luvia Decor <objednavky@luvia-decor.cz>',to,replyTo:'podpora@luvia-decor.cz',subject:`${label} · ${orderNo} | Luvia Decor`,html}),resend.emails.send({from:'Luvia Decor <objednavky@luvia-decor.cz>',to:seller,subject:`${label} · ${orderNo} | Luvia Decor`,html})]);
  const failed=results.find((r:any)=>r.status==='rejected'||r.value?.error); if(failed){const error=failed.status==='rejected'?failed.reason?.message:failed.value?.error?.message;throw new Error(error||'Resend odmítl e-mail.');}
  return { customer:true, seller:true, sentAt:new Date().toISOString() };
}
