import React, { useState } from 'react';
import { PackageSearch, ShoppingBag, Truck } from 'lucide-react';
import { AdminPage as LegacyAdminPage } from './AdminPageLegacy';
import { ShippingCouponManager } from '../components/ShippingCouponManager';
import { OrderStatusEnhancer } from '../components/OrderStatusEnhancer';
import { AllCouponsList } from '../components/AllCouponsList';
import { OrderTrackingManager } from '../components/OrderTrackingManager';
import { OrderStatusCategory } from '../components/OrderStatusCategory';
import { useApp } from '../context/AppContext';
export const AdminPage:React.FC=()=>{const{adminUser}=useApp();const[active,setActive]=useState<'main'|'statuses'|'tracking'|'shipping'>('main');return <><OrderStatusEnhancer/>{adminUser&&<div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-8"><div className="flex items-center gap-2 overflow-x-auto pb-2 border-b border-[#E8DFC8]"><button type="button" onClick={()=>setActive('main')}>Administrace</button><button type="button" onClick={()=>setActive('statuses')}><ShoppingBag className="w-4 h-4 inline"/> Stavy objednávek</button><button type="button" onClick={()=>setActive('tracking')}><PackageSearch className="w-4 h-4 inline"/> Sledování zásilek</button><button type="button" onClick={()=>setActive('shipping')}><Truck className="w-4 h-4 inline"/> Doprava a přepravci</button></div></div>}{active==='statuses'&&adminUser?<OrderStatusCategory/>:active==='tracking'&&adminUser?<OrderTrackingManager/>:<><LegacyAdminPage/><ShippingCouponManager/><AllCouponsList/></>}</>};