import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, Minus, Plus, Trash2, Truck, MapPinned, User, PackageCheck, MapPin, ShieldCheck, Tag, X, RefreshCw } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { DpdPickupWidget } from '../components/DpdPickupWidget';
import { PacketaPickupWidget } from '../components/PacketaPickupWidget';
import { PenguinBoxPickupWidget } from '../components/PenguinBoxPickupWidget';

type Method = 'address' | 'pickup_point' | 'box' | 'personal_pickup';
type Destination = 'cz' | 'sk';
type Shipping = { enabled?: boolean; address?: number; pickup_point?: number; box?: number; zaslatCarrier?: string; rate?: number };
const ZASLAT_CARRIERS: Record<string,string> = { PPL:'PPL', DPD:'DPD', GLS:'GLS', TOPTRANS:'TOPTRANS', UPS:'UPS', 'GLS-SK':'GLS-SK', LIFTAGO:'grid.online', FEDEX:'FedEx', WEDO:'One By Allegro', BALIKOVNA:'Balíkovna', ZASILKOVNA:'Zásilkovna', SPS:'SPS', PenguinBox:'PenguinBox' };
const ZASLAT_MAP_CARRIERS = new Set(['DPD','GLS','PPL','ZASILKOVNA','BALIKOVNA']);
const DEFAULT = { carriers: Object.fromEntries(Object.keys(ZASLAT_CARRIERS).map(k=>[k,{enabled:true,address:k==='PenguinBox'?0:0,pickup_point:k==='PenguinBox'?59:0,box:k==='PenguinBox'?59:0}])) as Record<string,Shipping>, personalPickup: { enabled: true, price: 0, label: 'Osobní odběr – Kroměříž' } };
const IBAN = 'CZ45550000000000963625011';
const input = 'w-full rounded-2xl border border-[#E5DCD2] bg-[#FCFAF7] px-4 py-3.5 text-sm text-[#302923] outline-none focus:border-[#9A7B58] focus:bg-white focus:ring-4 focus:ring-[#9A7B58]/10 placeholder:text-[#A79C91]';
const option = (active: boolean) => `relative rounded-2xl border p-4 text-left transition ${active ? 'border-[#9A7B58] bg-[#FBF6EF] shadow-sm' : 'border-[#E8E0D8] bg-white hover:border-[#C8B39B]'}`;
const normalizeCategory = (value: unknown) => String(value || '').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const vsOf = (o: any) => String(o?.orderNumber || o?.id || '').replace(/\D/g, '');
const qrOf = (o: any) => { const n = String(o?.orderNumber || o?.id || ''); const p = `SPD*1.0*ACC:${IBAN}*AM:${Number(o?.totalPrice || 0).toFixed(2)}*CC:CZK*X-VS:${vsOf(o)}*X-MSG:${n}`; return `https://api.qrserver.com/v1/create-qr-code/?size=280x280&margin=8&data=${encodeURIComponent(p)}`; };
const normalizePhone = (value: string) => value.replace(/[\s()-]/g, '');
const validInternationalPhone = (value: string) => /^\+[1-9]\d{7,14}$/.test(normalizePhone(value));

export const CheckoutCartPage: React.FC = () => {
  const { cart, cartTotal, removeFromCart, updateCartQuantity, clearCart, setPage, addToast, config } = useApp();
  const rawShipping: any = (config as any)?.shipping || {};
  const [destination, setDestination] = useState<Destination>('cz');
  const [carrier, setCarrier] = useState('PenguinBox');
  const [method, setMethod] = useState<Method>('box');
  const [point, setPoint] = useState<any>(null);
  const [picker, setPicker] = useState(false);
  const [zaslatRates, setZaslatRates] = useState<Record<string,any>>({});
  const [ratesLoading, setRatesLoading] = useState(false);
  const [ratesError, setRatesError] = useState('');
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [phone, setPhone] = useState(''); const [street, setStreet] = useState(''); const [city, setCity] = useState(''); const [zip, setZip] = useState(''); const [note, setNote] = useState('');
  const [termsAccepted, setTermsAccepted] = useState(false); const [privacyAcknowledged, setPrivacyAcknowledged] = useState(false); const [sending, setSending] = useState(false); const [done, setDone] = useState<any>(null);
  const [couponInput, setCouponInput] = useState(''); const [couponChecking, setCouponChecking] = useState(false); const [appliedCoupon, setAppliedCoupon] = useState<{code:string;type:'percent'|'fixed';value:number;categoryIds:string[];giftVoucher?:boolean}|null>(null);
  const shippingConfig: any = { ...DEFAULT, ...rawShipping, carriers: { ...DEFAULT.carriers, ...(rawShipping.carriers || {}) }, personalPickup: { ...DEFAULT.personalPickup, ...(rawShipping.personalPickup || {}) } };
  const entries: [string,Shipping][] = Object.entries(shippingConfig.carriers).filter(([n,c]: any)=>ZASLAT_CARRIERS[n] && c?.enabled !== false).map(([n,c]: any)=>[n,c]);
  const cfg: Shipping = shippingConfig.carriers?.[carrier] || {};
  const selectedRate = zaslatRates[carrier];
  const shipping = method === 'personal_pickup' ? Number(shippingConfig.personalPickup?.price || 0) : carrier === 'PenguinBox' ? 59 : Number(selectedRate?.price ?? cfg?.address ?? cfg?.pickup_point ?? cfg?.box ?? 0);
  const eligibleCouponSubtotal = useMemo(() => appliedCoupon?.categoryIds?.length ? cart.reduce((s,i) => appliedCoupon.categoryIds.some(c => normalizeCategory(c) === normalizeCategory(i.product.category)) ? s + Number(i.product.price || 0) * i.quantity : s, 0) : cartTotal, [cart, cartTotal, appliedCoupon]);
  const discount = appliedCoupon ? appliedCoupon.type === 'percent' ? Math.min(eligibleCouponSubtotal, Math.round(eligibleCouponSubtotal * appliedCoupon.value / 100)) : Math.min(eligibleCouponSubtotal, appliedCoupon.value) : 0;
  const total = Math.max(0, cartTotal - discount + shipping);

  const loadRates = async () => {
    setRatesLoading(true); setRatesError('');
    try {
      const r = await fetch('/api/orders?action=rates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ fromCountry:'CZ', toCountry:destination==='sk'?'SK':'CZ', packages:[{weight:1,width:20,height:20,length:20}] })});
      const d = await r.json().catch(()=>null);
      if (!r.ok) throw new Error(d?.error || d?.message || 'Nabídku dopravy se nepodařilo načíst.');
      const rawRates = Array.isArray(d?.rates) ? d.rates : Array.isArray(d?.data?.rates) ? d.data.rates : [];
      const map: Record<string,any> = {};
      for (const rate of rawRates) {
        const key = String(rate?.carrier || '').trim().toUpperCase();
        if (!key) continue;
        map[key] = { ...rate, price:Number(rate?.price_vat?.value ?? rate?.price?.value ?? 0) };
      }
      setZaslatRates(map);
      if (carrier !== 'PenguinBox' && !map[carrier]) {
        const first = entries.find(([n])=>n !== 'PenguinBox' && map[n]);
        if (first) { setCarrier(first[0]); setMethod('address'); setPoint(null); }
      }
    } catch (e:any) {
      setRatesError(e?.message || 'Zaslat.cz momentálně nevrátilo nabídku dopravy.');
      addToast('error','Dopravu Zaslat se nepodařilo načíst',e?.message || 'PenguinBox je stále dostupný.');
    } finally { setRatesLoading(false); }
  };
  useEffect(()=>{ loadRates(); },[destination,cart.length,cart.map(i=>`${i.product.id}:${i.quantity}`).join('|')]);
  useEffect(()=>{ if(!entries.some(([n])=>n===carrier)) { setCarrier('PenguinBox'); setMethod('box'); } },[entries.length,carrier]);

  const chooseDestination = (d: Destination) => { setDestination(d); setPoint(null); setPicker(false); setMethod('box'); setCarrier('PenguinBox'); };
  const chooseCarrier = (c: string) => { setCarrier(c); setPoint(null); setPicker(c === 'PenguinBox'); setMethod(c === 'PenguinBox' ? 'box' : 'address'); };
  const chooseMethod = (m: Method) => { if (m==='personal_pickup') { setMethod(m); setPoint(null); setPicker(false); return; } setMethod(m); setPoint(null); setPicker(m==='pickup_point'||m==='box'); };

  const applyCoupon = async () => {
    const code = couponInput.trim().toUpperCase(); if (!code) return addToast('error','Zadejte slevový kód','Napište kód a klikněte na Použít.'); setCouponChecking(true);
    try { const r=await fetch('/api/coupons/validate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,items:cart.map(i=>({productId:i.product.id,category:i.product.category,price:i.product.price,quantity:i.quantity}))})}); const d=await r.json().catch(()=>null); if(!r.ok||!d?.valid) throw new Error(d?.error||'Slevový kód je neplatný nebo deaktivovaný.'); setAppliedCoupon({code:d.code,type:d.type==='fixed'?'fixed':'percent',value:Number(d.value)||0,categoryIds:Array.isArray(d.categoryIds)?d.categoryIds:[],giftVoucher:Boolean(d.giftVoucher)}); addToast('success','Slevový kód použit','Sleva byla započtena.'); } catch(e:any){setAppliedCoupon(null);addToast('error','Kód se nepodařilo použít',e?.message||'Zkuste to znovu.');} finally{setCouponChecking(false);} 
  };

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    if(!cart.length) return addToast('error','Košík je prázdný','Přidejte nejprve produkt.');
    if(!name.trim()||!email.trim()||!phone.trim()) return addToast('error','Chybí údaje','Jméno a příjmení, e-mail a telefon jsou povinné.');
    if(!validInternationalPhone(phone)) return addToast('error','Neplatný telefon','Telefon zadejte včetně mezinárodní předvolby.');
    if(!carrier||!entries.some(([n])=>n===carrier)) return addToast('error','Vyberte přepravce','Vyberte dostupného přepravce.');
    if(method==='address'&&(!street.trim()||!city.trim()||!zip.trim())) return addToast('error','Chybí adresa','Ulice, město a PSČ jsou povinné.');
    if((method==='pickup_point'||method==='box')&&!point) return addToast('error','Vyberte výdejní místo','Vyberte výdejní místo nebo box.');
    if(!termsAccepted||!privacyAcknowledged) return addToast('error','Potvrďte dokumenty','Pro odeslání objednávky je nutné potvrdit Obchodní podmínky a GDPR.');
    setSending(true);
    try {
      const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer:{fullName:name.trim(),email:email.trim(),phone:normalizePhone(phone),street:method==='personal_pickup'?'':street.trim(),city:method==='personal_pickup'?'':city.trim(),zip:method==='personal_pickup'?'':zip.trim(),country:destination==='sk'?'Slovensko':'Česká republika',note:note.trim()},items:cart.map(i=>({productId:i.product.id,title:i.product.title,price:i.product.price,quantity:i.quantity,category:i.product.category,imageUrl:i.product.imageUrl,customNote:i.customNote})),couponCode:appliedCoupon?.code,paymentMethod:'bank_transfer',delivery:method==='personal_pickup'?{method}:{method,carrier,country:destination==='sk'?'SK':'CZ',zaslatServiceId:selectedRate?.service_id,zaslatService:selectedRate?.service,zaslatRate:selectedRate?.price,zaslatPickupBranch:point?.code||point?.carrierPickupPointId||undefined,...(point?{pickupPoint:String(point.name||point.address||point.id||'Vybrané místo'),pickupPointId:point.id||point.carrierPickupPointId||undefined}: {})},termsAccepted:true,privacyAcknowledged:true})});
      const d=await r.json().catch(()=>null); if(!r.ok||!d?.order) throw new Error(d?.error||'Objednávku se nepodařilo odeslat.'); setDone(d.order); clearCart(); addToast('success','Objednávka přijata','Objednávka byla úspěšně odeslána.');
    } catch(err:any){addToast('error','Chyba při odesílání',err?.message||'Zkuste to znovu.');} finally{setSending(false);}
  };

  if(done) return <div className="min-h-[70vh] bg-[#FAF8F5] flex items-center justify-center px-4 py-14"><div className="w-full max-w-3xl bg-white rounded-[2rem] border border-[#E6DDD3] shadow-xl p-7 sm:p-12 text-center"><div className="w-16 h-16 mx-auto rounded-full bg-[#F4EEE5] flex items-center justify-center"><CheckCircle2 className="w-8 h-8 text-[#806746]"/></div><p className="text-[11px] uppercase tracking-[.22em] text-[#9A7B58] mt-5">Číslo objednávky · {done.orderNumber}</p><h1 className="font-editorial text-3xl sm:text-4xl font-bold mt-3">Objednávka byla přijata</h1><p className="text-sm text-[#7B7067] mt-3">Děkujeme za Váš nákup. Pro dokončení objednávky proveďte bankovní převod.</p><div className="mt-8 rounded-2xl bg-[#FAF7F2] border border-[#E9E0D6] p-5 text-left space-y-3 text-sm"><p><b>Číslo účtu:</b> 963625011/5500</p><p><b>IBAN:</b> CZ45 5500 0000 0096 3625 011</p><p><b>Variabilní symbol:</b> {vsOf(done)}</p><p><b>Částka:</b> {Number(done.totalPrice||0).toLocaleString('cs-CZ')} Kč</p><p><b>Poznámka pro příjemce:</b> {done.orderNumber}</p>{Number(done.discount||0)>0&&<p className="text-emerald-700"><b>Sleva:</b> −{Number(done.discount).toLocaleString('cs-CZ')} Kč</p>}</div><img src={qrOf(done)} alt="QR platba" width="280" height="280" className="mx-auto mt-7 rounded-2xl border border-[#E3D8CA]"/><button type="button" onClick={()=>setPage('home')} className="mt-8 px-7 py-3.5 rounded-2xl bg-[#302923] text-white font-semibold">Zpět na úvod</button></div></div>;
  if(!cart.length) return <div className="min-h-[60vh] bg-[#FAF8F5] flex items-center justify-center px-4"><div className="text-center"><PackageCheck className="w-12 h-12 mx-auto text-[#806746]"/><h1 className="font-editorial text-4xl font-bold mt-5">Košík je prázdný</h1><p className="mt-3 text-[#7B7067]">Vyberte si něco krásného z naší nabídky.</p><button onClick={()=>setPage('catalog')} className="mt-7 px-7 py-3.5 rounded-2xl bg-[#302923] text-white font-semibold">Prohlédnout produkty</button></div></div>;
  return <div className="bg-[#FAF8F5] py-8 sm:py-12"><div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8"><button type="button" onClick={()=>setPage('catalog')} className="flex items-center gap-2 text-sm text-[#85786E] mb-7"><ArrowLeft className="w-4 h-4"/> Zpět do nabídky</button><div className="mb-8"><p className="text-[10px] uppercase tracking-[.28em] text-[#9A7B58] font-bold">Luvia Decor · bezpečná objednávka</p><h1 className="font-editorial text-4xl sm:text-5xl font-bold mt-2">Váš košík</h1></div><form onSubmit={submit} className="grid lg:grid-cols-[1fr_430px] gap-6 lg:gap-8 items-start"><section className="bg-white rounded-[1.75rem] border border-[#E6DDD3] shadow-sm overflow-hidden"><div className="p-5 sm:p-7 border-b border-[#EEE7DE] flex justify-between"><h2 className="font-editorial text-2xl font-bold">Vaše produkty</h2><span className="rounded-full bg-[#F5EFE8] px-3 py-1.5 text-xs font-semibold">{cart.reduce((s,i)=>s+i.quantity,0)} ks</span></div><div className="p-4 sm:p-7 space-y-3">{cart.map(i=><div key={i.product.id} className="rounded-2xl border border-[#EEE7DE] bg-[#FCFAF7] p-3 sm:p-4 flex gap-3 items-center"><div className="w-20 h-20 sm:w-24 sm:h-24 rounded-xl bg-[#F3EEE8] overflow-hidden shrink-0">{i.product.imageUrl?<img src={i.product.imageUrl} alt="" className="w-full h-full object-cover"/>:<PackageCheck className="m-7 text-[#B4A99E"/>}</div><div className="min-w-0 flex-1"><b className="break-words">{i.product.title}</b><div className="text-sm text-[#9A7B58] mt-1">{Number(i.product.price).toLocaleString('cs-CZ')} Kč / ks</div><div className="mt-3 inline-flex items-center rounded-xl border border-[#E4DBD1] bg-white overflow-hidden"><button type="button" onClick={()=>updateCartQuantity(i.product.id,i.quantity-1)} className="w-9 h-9"><Minus className="w-3.5 h-3.5 mx-auto"/></button><span className="w-9 text-center text-sm font-semibold">{i.quantity}</span><button type="button" onClick={()=>updateCartQuantity(i.product.id,i.quantity+1)} className="w-9 h-9"><Plus className="w-3.5 h-3.5 mx-auto"/></button></div></div><div className="text-right self-stretch flex flex-col items-end justify-between"><button type="button" onClick={()=>removeFromCart(i.product.id)} className="p-2 text-[#A59A91] hover:text-rose-600"><Trash2 className="w-4 h-4"/></button><b className="text-sm">{(Number(i.product.price)*i.quantity).toLocaleString('cs-CZ')} Kč</b></div></div>)}</div></section>
  <section className="bg-white rounded-[1.75rem] border border-[#E6DDD3] shadow-sm p-5 sm:p-7 space-y-6 lg:sticky lg:top-6"><h2 className="font-editorial text-2xl font-bold">Dokončení objednávky</h2><div><div className="flex items-center gap-2 mb-3"><User className="w-4 h-4 text-[#9A7B58]"/><b>Kontaktní údaje</b></div><div className="space-y-3"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Jméno a příjmení *" className={input}/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="E-mail *" className={input}/><input required type="tel" inputMode="tel" autoComplete="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Telefon včetně předvolby, např. +420 123 456 789 *" className={input}/></div></div>
  <div><div className="flex items-center gap-2 mb-3"><Truck className="w-4 h-4 text-[#9A7B58]"/><b>Země doručení *</b></div><div className="grid grid-cols-2 gap-2"><button type="button" onClick={()=>chooseDestination('cz')} className={option(destination==='cz')}><b>🇨🇿 Česká republika</b><span className="block text-[11px] text-[#8B8178] mt-1">Zaslat.cz</span></button><button type="button" onClick={()=>chooseDestination('sk')} className={option(destination==='sk')}><b>🇸🇰 Slovensko</b><span className="block text-[11px] text-[#8B8178] mt-1">Zaslat.cz</span></button></div></div>
  <div><div className="flex items-center gap-2 mb-3"><Truck className="w-4 h-4 text-[#9A7B58]"/><b>Přepravce *</b></div>{ratesLoading?<div className="rounded-2xl bg-[#FAF7F2] p-4 text-sm text-[#7B7067] flex items-center gap-2"><RefreshCw className="w-4 h-4 animate-spin"/> Načítám aktuální nabídky Zaslat.cz…</div>:<><div className="grid grid-cols-2 gap-2">{entries.map(([n])=>{const rate=zaslatRates[n]; const isPenguin=n==='PenguinBox'; return <button type="button" key={n} onClick={()=>chooseCarrier(n)} className={option(carrier===n)}><b>{isPenguin?'PenguinBox':ZASLAT_CARRIERS[n]||n}</b><span className="block text-[11px] text-[#8B8178] mt-2">{isPenguin?'Vlastní box · 59 Kč':rate?`${Number(rate.price).toLocaleString('cs-CZ')} Kč · ${rate.service||'Zaslat'}`:'Zaslat.cz · dostupnost se ověřuje'}</span></button>})}</div>{ratesError&&<p className="mt-2 text-[11px] text-amber-700">Zaslat.cz nabídku nyní nevrátilo. Dopravci zůstávají zobrazeni a po obnovení nabídky se doplní jejich aktuální cena.</p>}</>}</div>
  <div><div className="flex items-center gap-2 mb-3"><MapPinned className="w-4 h-4 text-[#9A7B58]"/><b>Způsob doručení *</b></div><div className="grid grid-cols-2 gap-2"><button type="button" onClick={()=>chooseMethod('address')} disabled={carrier==='PenguinBox'} className={`${option(method==='address')} ${carrier==='PenguinBox'?'opacity-50 cursor-not-allowed':''}`}><b>Na adresu</b><span className="block text-[11px] mt-1">{carrier==='PenguinBox'?'—':`${Number(selectedRate?.price??cfg?.address??0).toLocaleString('cs-CZ')} Kč`}</span></button>{carrier==='PenguinBox'?<button type="button" onClick={()=>chooseMethod('box')} className={option(method==='box')}><b>Penguin Box</b><span className="block text-[11px] mt-1">59 Kč · pouze do boxu</span></button>:ZASLAT_MAP_CARRIERS.has(carrier)?<button type="button" onClick={()=>chooseMethod('pickup_point')} className={option(method==='pickup_point')}><b>Výdejní místo / box</b><span className="block text-[11px] mt-1">Mapa Zaslat.cz</span></button>:null}{destination==='cz'&&shippingConfig.personalPickup?.enabled!==false&&<button type="button" onClick={()=>chooseMethod('personal_pickup')} className={option(method==='personal_pickup')}><b>{shippingConfig.personalPickup?.label||'Osobní odběr – Kroměříž'}</b><span className="block text-[11px] mt-1">{Number(shippingConfig.personalPickup?.price||0).toLocaleString('cs-CZ')} Kč</span></button>}</div></div>
  {method==='address'&&carrier!=='PenguinBox'&&<div className="space-y-3"><input required value={street} onChange={e=>setStreet(e.target.value)} placeholder={destination==='sk'?'Ulice a číslo popisné (Slovensko) *':'Ulice a číslo popisné *'} className={input}/><div className="grid grid-cols-2 gap-2"><input required value={city} onChange={e=>setCity(e.target.value)} placeholder="Město *" className={input}/><input required value={zip} onChange={e=>setZip(e.target.value)} placeholder="PSČ *" className={input}/></div></div>}
  {(method==='pickup_point'||method==='box')&&<div className="rounded-2xl bg-[#FAF7F2] border border-[#E5DCD2] p-4 text-xs"><MapPin className="w-4 h-4 inline text-[#9A7B58] mr-2"/>{point?<><b>Vybráno:</b> {String(point.name||point.address||point.id||'Místo')}</>:<>Mapa {carrier} se otevře automaticky.</>}</div>}
  {picker&&method==='pickup_point'&&(carrier==='Zásilkovna'||carrier==='ZASILKOVNA'?<PacketaPickupWidget country={destination==='sk'?'sk':'cz'} onSelect={p=>{setPoint(p);setPicker(false);}}/>:carrier==='DPD'?<DpdPickupWidget initialCarrier="DPD" onSelect={p=>{setPoint(p);setPicker(false);}}/>:null)}
  {picker&&method==='box'&&carrier==='PenguinBox'&&<PenguinBoxPickupWidget onSelect={p=>{setPoint(p);setPicker(false);}}/>}
  <div><label className="text-xs font-semibold">Poznámka <span className="font-normal text-[#9A8F85]">(nepovinná)</span></label><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Poznámka k objednávce" className={`${input} min-h-24 mt-2`}/></div>
  <div><label className="text-xs font-semibold block mb-2">Slevový kód / dárkový poukaz</label>{appliedCoupon?<div className="flex items-center justify-between gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3"><span className="flex items-center gap-2 text-sm font-semibold text-emerald-700"><Tag className="w-4 h-4"/>{appliedCoupon.code}<span>(−{appliedCoupon.type==='percent'?`${appliedCoupon.value} %`:`${appliedCoupon.value.toLocaleString('cs-CZ')} Kč`})</span></span><button type="button" onClick={()=>setAppliedCoupon(null)}><X className="w-4 h-4 text-emerald-700"/></button></div>:<div className="flex gap-2"><input value={couponInput} onChange={e=>setCouponInput(e.target.value.toUpperCase())} placeholder="Např. LUVIA10" className={`${input} flex-1 uppercase`}/><button type="button" onClick={applyCoupon} disabled={couponChecking} className="rounded-2xl bg-[#302923] px-5 text-white text-sm font-semibold disabled:opacity-50">{couponChecking?<RefreshCw className="w-4 h-4 animate-spin"/>:'Použít'}</button></div>}</div>
  <div className="border-t border-[#EEE7DE] pt-5 space-y-2 text-sm"><div className="flex justify-between"><span>Zboží</span><b>{cartTotal.toLocaleString('cs-CZ')} Kč</b></div>{discount>0&&<div className="flex justify-between text-emerald-700"><span>Sleva ({appliedCoupon?.code})</span><b>−{discount.toLocaleString('cs-CZ')} Kč</b></div>}<div className="flex justify-between"><span>Doprava</span><b>{shipping.toLocaleString('cs-CZ')} Kč</b></div><div className="flex justify-between text-lg pt-2"><span>Celkem</span><b>{total.toLocaleString('cs-CZ')} Kč</b></div><div className="text-xs text-[#7B7067]">Platba: bankovní převod · doprava přes Zaslat.cz</div></div>
  <div className="rounded-2xl border border-[#E5DCD2] bg-[#FCFAF7] p-4 space-y-3"><label className="flex items-start gap-3 text-sm cursor-pointer"><input type="checkbox" checked={termsAccepted} onChange={e=>setTermsAccepted(e.target.checked)} required className="mt-1 h-4 w-4 accent-[#806746]"/><span>Souhlasím s <button type="button" onClick={()=>setPage('terms')} className="font-semibold text-[#806746] underline underline-offset-2">Obchodními podmínkami</button>.</span></label><label className="flex items-start gap-3 text-sm cursor-pointer"><input type="checkbox" checked={privacyAcknowledged} onChange={e=>setPrivacyAcknowledged(e.target.checked)} required className="mt-1 h-4 w-4 accent-[#806746]"/><span>Seznámil/a jsem se s <button type="button" onClick={()=>setPage('privacy')} className="font-semibold text-[#806746] underline underline-offset-2">Ochranou osobních údajů (GDPR)</button>.</span></label><p className="text-[11px] leading-5 text-[#81766D] flex gap-2"><ShieldCheck className="w-4 h-4 shrink-0 text-[#9A7B58]"/>Potvrzení GDPR zde není souhlasem se zpracováním osobních údajů; údaje potřebné pro objednávku zpracováváme na příslušném zákonném právním základě.</p></div><button disabled={sending||!termsAccepted||!privacyAcknowledged} className="w-full rounded-2xl bg-[#302923] text-white py-4 font-bold disabled:opacity-50">{sending?'Odesílám objednávku…':'Odeslat objednávku'}</button></section></form></div></div>;
};