import React, { useEffect, useMemo, useState } from 'react';
import { useApp } from '../context/AppContext';
import { ArrowRight, Check, ChevronRight, Heart, LogOut, MapPin, Package, Plus, RefreshCw, Settings, ShieldCheck, Sparkles, Star, Ticket, Trash2, User, WalletCards, X } from 'lucide-react';
import type { CustomerAccount, CustomerAddress, CustomerCollection, Order, Product } from '../types';

type Tab='overview'|'orders'|'favorites'|'collections'|'addresses'|'benefits'|'profile'|'settings';
const styles=['Elegantní','Přírodní','Moderní','Minimalistický','Romantický','Rustikální'];
const colors=['Bílá','Béžová','Zlatá','Černá','Zelená','Růžová'];
const statusLabels:Record<string,string>={nova:'Objednávka přijata',zpracovava_se:'Zpracováváme',zaplaceno:'Zaplaceno',u_prepravce:'U dopravce',odeslano:'Odesláno',dokonceno:'Dokončeno',zruseno:'Zrušeno'};
const money=(n:number)=>Number(n||0).toLocaleString('cs-CZ',{minimumFractionDigits:2,maximumFractionDigits:2})+' Kč';

export const CustomerAccountPage:React.FC=()=>{
 const {products,setPage,addToCart,addToast}=useApp();
 const [account,setAccount]=useState<CustomerAccount|null>(()=>{try{return JSON.parse(localStorage.getItem('luvia_customer')||'null')}catch{return null}});
 const [token,setToken]=useState(()=>localStorage.getItem('luvia_customer_token')||'');
 const [tab,setTab]=useState<Tab>('overview');
 const [orders,setOrders]=useState<Order[]>([]); const [vouchers,setVouchers]=useState<any[]>([]); const [coupons,setCoupons]=useState<any[]>([]);
 const [authMode,setAuthMode]=useState<'login'|'register'>('login'); const [loading,setLoading]=useState(false); const [message,setMessage]=useState('');
 const [form,setForm]=useState({name:'',email:'',phone:'',password:'',currentPassword:'',newPassword:''});
 const [address,setAddress]=useState<Partial<CustomerAddress>>({label:'Domů',fullName:'',phone:'',street:'',city:'',zip:'',country:'Česká republika'});
 const [showAddress,setShowAddress]=useState(false); const [collectionName,setCollectionName]=useState(''); const [showCollection,setShowCollection]=useState(false);
 const [preferences,setPreferences]=useState({styles:[] as string[],colors:[] as string[]});
 const [saving,setSaving]=useState(false);

 const authHeaders=()=>token?{'Authorization':`Bearer ${token}`}:{};
 const persist=(next:any)=>{setAccount(next);try{localStorage.setItem('luvia_customer',JSON.stringify(next))}catch{}};
 const loadAccount=async(t=token)=>{if(!t)return;try{const r=await fetch('/api/customer/me',{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});if(!r.ok)throw new Error();const d=await r.json();persist(d.user);setPreferences(d.user.preferences||{styles:[],colors:[]});setOrders(Array.isArray(d.orders)?d.orders:[]);setVouchers(Array.isArray(d.vouchers)?d.vouchers:[]);setCoupons(Array.isArray(d.coupons)?d.coupons:[])}catch{localStorage.removeItem('luvia_customer_token');localStorage.removeItem('luvia_customer');setToken('');setAccount(null)}};
 useEffect(()=>{if(token)loadAccount(token)},[]);
 const doAuth=async()=>{setLoading(true);setMessage('');try{const endpoint=authMode==='login'?'/api/customer/login':'/api/customer/register';const body=authMode==='login'?{email:form.email,password:form.password}:{email:form.email,password:form.password,name:form.name,phone:form.phone};const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Přihlášení se nepodařilo.');localStorage.setItem('luvia_customer_token',d.token);setToken(d.token);persist(d.user);setPreferences(d.user.preferences||{styles:[],colors:[]});setMessage('');}catch(e:any){setMessage(e?.message||'Nastala chyba.')}finally{setLoading(false)}};
 const save=async(updates:any)=>{setSaving(true);try{const r=await fetch('/api/customer/me',{method:'PUT',headers:{'Content-Type':'application/json',...authHeaders()},body:JSON.stringify(updates)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Uložení se nepodařilo.');persist(d.user);if(d.user.preferences)setPreferences(d.user.preferences);addToast('success','Uloženo','Vaše údaje byly úspěšně aktualizovány.')}catch(e:any){addToast('error','Nepodařilo se uložit',e.message)}finally{setSaving(false)}};
 const logout=async()=>{await fetch('/api/customer/logout',{method:'POST',headers:authHeaders()}).catch(()=>{});localStorage.removeItem('luvia_customer_token');localStorage.removeItem('luvia_customer');setToken('');setAccount(null);setOrders([]);setVouchers([]);setCoupons([])};
 const favoriteProducts=useMemo(()=>products.filter(p=>account?.favorites?.includes(p.id)),[products,account]);
 const points=useMemo(()=>Math.floor(orders.filter(o=>o.status!=='zruseno').reduce((s,o)=>s+Number(o.subtotal||0),0)/10),[orders]);
 const level=points>=1000?'Luvia VIP':points>=500?'Luvia Lover':points>=200?'Luvia Fan':'Začínáme';
 const nextLevel=points<200?200:points<500?500:points<1000?1000:1000;
 const progress=nextLevel===1000&&points>=1000?100:Math.min(100,Math.round(points/nextLevel*100));
 const toggle=(key:'styles'|'colors',value:string)=>setPreferences(p=>({...p,[key]:p[key].includes(value)?p[key].filter(x=>x!==value):[...p[key],value]}));
 const addAddress=async()=>{if(!address.street||!address.city||!address.zip)return addToast('error','Doplňte adresu','Ulice, město a PSČ jsou povinné.');const item={...address,id:`addr-${Date.now()}`} as CustomerAddress;await save({addresses:[...(account?.addresses||[]),item]});setShowAddress(false);setAddress({label:'Domů',fullName:'',phone:'',street:'',city:'',zip:'',country:'Česká republika'})};
 const removeAddress=(id:string)=>save({addresses:(account?.addresses||[]).filter(a=>a.id!==id)});
 const createCollection=async()=>{if(!collectionName.trim())return;const now=new Date().toISOString();const item:CustomerCollection={id:`col-${Date.now()}`,name:collectionName.trim(),productIds:[],createdAt:now,updatedAt:now};await save({collections:[...(account?.collections||[]),item]});setCollectionName('');setShowCollection(false)};
 const deleteCollection=(id:string)=>save({collections:(account?.collections||[]).filter(c=>c.id!==id)});
 const toggleCollectionProduct=async(col:CustomerCollection,pid:string)=>{const next=col.productIds.includes(pid)?col.productIds.filter(x=>x!==pid):[...col.productIds,pid];await save({collections:(account?.collections||[]).map(c=>c.id===col.id?{...c,productIds:next,updatedAt:new Date().toISOString()}:c)})};
 const repeatOrder=(order:Order)=>{let count=0;order.items.forEach(i=>{const p=products.find(x=>x.id===i.productId);if(p&&p.inStock!==false){addToCart(p,i.quantity,i.customNote);count+=i.quantity}});addToast(count?'success':'error',count?'Objednávka připravena':'Nic není skladem',count?'Dostupné položky byly přidány do košíku.':'Produkty z této objednávky již nejsou dostupné.');if(count)setPage('cart')};

 if(!account)return <div className="min-h-[70vh] px-4 py-12 bg-[#FCFAF7]"><div className="max-w-md mx-auto bg-white rounded-3xl border border-[#E5DACD] shadow-xl p-6 sm:p-8"><div className="text-center mb-7"><div className="mx-auto w-14 h-14 rounded-2xl bg-[#F2E9DE] flex items-center justify-center text-[#8C7355]"><User className="w-7 h-7"/></div><h1 className="font-editorial text-3xl font-bold mt-4 text-[#241E1A]">{authMode==='login'?'Vítejte zpět':'Vytvořte si účet'}</h1><p className="text-sm text-[#76685D] mt-2">{authMode==='login'?'Přihlaste se do svého osobního prostoru Luvia Decor.':'Ukládejte objednávky, oblíbené produkty, adresy a získávejte Luvia Points.'}</p></div><div className="space-y-3">{authMode==='register'&&<><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Jméno a příjmení" className="w-full rounded-xl border border-[#DED3C7] px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-[#C5A880]/40"/><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Telefon" className="w-full rounded-xl border border-[#DED3C7] px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-[#C5A880]/40"/></>}<input value={form.email} onChange={e=>setForm({...form,email:e.target.value})} type="email" placeholder="E-mail" className="w-full rounded-xl border border-[#DED3C7] px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-[#C5A880]/40"/><input value={form.password} onChange={e=>setForm({...form,password:e.target.value})} type="password" placeholder="Heslo (min. 8 znaků)" onKeyDown={e=>e.key==='Enter'&&doAuth()} className="w-full rounded-xl border border-[#DED3C7] px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-[#C5A880]/40"/>{message&&<div className="rounded-xl bg-red-50 border border-red-100 text-red-700 px-4 py-3 text-xs">{message}</div>}<button disabled={loading} onClick={doAuth} className="w-full rounded-xl bg-[#241E1A] text-white py-3.5 font-bold text-sm disabled:opacity-60">{loading?'Pracuji…':authMode==='login'?'Přihlásit se':'Vytvořit účet'}</button></div><div className="text-center mt-5 text-sm text-[#76685D]">{authMode==='login'?'Nemáte účet?':'Už máte účet?'} <button onClick={()=>{setAuthMode(authMode==='login'?'register':'login');setMessage('')}} className="font-bold text-[#8C7355] underline underline-offset-2">{authMode==='login'?'Vytvořit účet':'Přihlásit se'}</button></div><div className="mt-6 pt-5 border-t border-[#EEE6DD] text-center text-[11px] text-[#95877A] flex items-center justify-center gap-1.5"><ShieldCheck className="w-3.5 h-3.5"/> Heslo je uloženo zabezpečeně a účet můžete kdykoli přestat používat.</div></div></div>;

 const tabs:[Tab,string,React.ElementType][]=[['overview','Přehled',Sparkles],['orders','Objednávky',Package],['favorites','Oblíbené',Heart],['collections','Moje kolekce',Star],['addresses','Adresy',MapPin],['benefits','Luvia Points',WalletCards],['profile','Můj profil',User],['settings','Nastavení',Settings]];
 return <div className="min-h-[75vh] bg-[#FCFAF7] px-4 sm:px-6 py-7 sm:py-10"><div className="max-w-7xl mx-auto"><div className="flex flex-col lg:flex-row gap-6">
 <aside className="lg:w-64 shrink-0"><div className="bg-[#241E1A] text-[#FAF7F2] rounded-3xl p-5 shadow-lg"><div className="flex items-center gap-3 mb-5"><div className="w-11 h-11 rounded-2xl bg-[#8C7355] flex items-center justify-center font-bold text-lg">{account.name.slice(0,1).toUpperCase()}</div><div className="min-w-0"><p className="font-bold truncate">{account.name}</p><p className="text-[11px] text-[#CDBEAF] truncate">{account.email}</p></div></div><div className="rounded-2xl bg-white/10 border border-white/10 p-3 mb-4"><div className="flex justify-between text-xs"><span>{level}</span><span>{points} bodů</span></div><div className="h-1.5 bg-white/10 rounded-full mt-2 overflow-hidden"><div className="h-full bg-[#C5A880] rounded-full" style={{width:`${progress}%`}}/></div>{points<1000&&<p className="text-[10px] text-[#CDBEAF] mt-2">Ještě {Math.max(0,nextLevel-points)} bodů do další úrovně</p>}</div><div className="space-y-1">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-left text-sm transition ${tab===id?'bg-white text-[#241E1A] font-bold':'text-[#D9CDC0] hover:bg-white/10'}`}><Icon className="w-4 h-4"/>{label}</button>)}</div><button onClick={logout} className="w-full mt-4 pt-4 border-t border-white/10 flex items-center gap-3 px-3 py-2.5 text-sm text-[#D9CDC0] hover:text-white"><LogOut className="w-4 h-4"/> Odhlásit se</button></div></aside>
 <main className="flex-1 min-w-0"><div className="flex items-center justify-between gap-4 mb-6"><div><p className="text-[11px] uppercase tracking-[0.2em] text-[#9A8878] font-bold">Můj Luvia</p><h1 className="font-editorial text-3xl sm:text-4xl font-bold text-[#241E1A]">{tabs.find(x=>x[0]===tab)?.[1]}</h1></div><button onClick={()=>loadAccount()} className="p-2.5 rounded-xl border border-[#E0D6CA] bg-white text-[#8C7355]" title="Obnovit"><RefreshCw className="w-4 h-4"/></button></div>
 {tab==='overview'&&<div className="space-y-5"><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3"><Stat icon={Package} title="Objednávky" value={orders.length}/><Stat icon={Heart} title="Oblíbené" value={account.favorites.length}/><Stat icon={WalletCards} title="Luvia Points" value={points}/><Stat icon={Ticket} title="Výhody" value={coupons.length+vouchers.length}/></div>{orders[0]&&<Card title="Poslední objednávka"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><p className="font-bold text-[#241E1A]">{orders[0].orderNumber}</p><p className="text-xs text-[#897A6E] mt-1">{new Date(orders[0].createdAt).toLocaleDateString('cs-CZ')} · {statusLabels[orders[0].status]||orders[0].status}</p><p className="font-bold mt-2">{money(orders[0].totalPrice)}</p></div><button onClick={()=>setTab('orders')} className="inline-flex items-center gap-2 text-sm font-bold text-[#8C7355]">Detail objednávky <ArrowRight className="w-4 h-4"/></button></div></Card>}<Card title="✨ Vybráno pro vás"><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{products.filter(p=>p.inStock!==false).slice(0,4).map(p=><MiniProduct key={p.id} product={p} onClick={()=>{addToCart(p);setPage('cart')}}/>)}</div></Card></div>}
 {tab==='orders'&&<div className="space-y-3">{orders.length===0?<Empty icon={Package} text="Zatím nemáte žádné objednávky."/>:orders.map(o=><Card key={o.id}><div className="flex flex-col md:flex-row md:items-center justify-between gap-4"><div><p className="font-bold">{o.orderNumber}</p><p className="text-xs text-[#897A6E] mt-1">{new Date(o.createdAt).toLocaleDateString('cs-CZ')} · {statusLabels[o.status]||o.status}</p><p className="font-bold mt-2">{money(o.totalPrice)}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>repeatOrder(o)} className="inline-flex items-center gap-2 rounded-xl bg-[#241E1A] text-white px-3 py-2 text-xs font-bold"><RefreshCw className="w-3.5 h-3.5"/> Objednat znovu</button><span className="inline-flex items-center gap-2 rounded-xl bg-[#F2ECE4] px-3 py-2 text-xs font-bold text-[#67574A]"><Package className="w-3.5 h-3.5"/> {statusLabels[o.status]||o.status}</span></div></div><div className="mt-4 pt-4 border-t border-[#EEE7DF] grid sm:grid-cols-2 gap-2">{o.items.map((i,idx)=><div key={idx} className="text-xs text-[#64574C] flex justify-between gap-3"><span>{i.title} × {i.quantity}</span><span className="font-semibold">{money(i.price*i.quantity)}</span></div>)}</div></Card>)}</div>}
 {tab==='favorites'&&<div>{favoriteProducts.length===0?<Empty icon={Heart} text="Zatím nemáte žádné oblíbené produkty."/>:<div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-4">{favoriteProducts.map(p=><div key={p.id} className="bg-white rounded-2xl border border-[#E4D9CD] overflow-hidden"><img src={p.imageUrl} alt="" className="w-full aspect-square object-cover"/><div className="p-3"><p className="font-bold text-sm line-clamp-2">{p.title}</p><p className="font-bold mt-2">{money(p.price)}</p><button onClick={()=>{addToCart(p);setPage('cart')}} className="w-full mt-3 rounded-xl bg-[#241E1A] text-white py-2 text-xs font-bold">Do košíku</button></div></div>)}</div>}</div>}
 {tab==='collections'&&<div className="space-y-4"><div className="flex justify-end"><button onClick={()=>setShowCollection(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#241E1A] text-white px-4 py-2.5 text-sm font-bold"><Plus className="w-4 h-4"/> Nová kolekce</button></div>{(account.collections||[]).length===0?<Empty icon={Star} text="Vytvořte si první vlastní kolekci produktů."/>:(account.collections||[]).map(c=><Card key={c.id} title={c.name} action={<button onClick={()=>deleteCollection(c.id)} className="text-red-500 p-1"><Trash2 className="w-4 h-4"/></button>}><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{products.slice(0,8).map(p=><button key={p.id} onClick={()=>toggleCollectionProduct(c,p.id)} className={`text-left rounded-xl border overflow-hidden ${c.productIds.includes(p.id)?'border-[#8C7355] ring-2 ring-[#8C7355]/20':'border-[#E7DDD2]'}`}><img src={p.imageUrl} alt="" className="w-full aspect-square object-cover"/><div className="p-2 flex items-center justify-between gap-1"><span className="text-[11px] font-semibold line-clamp-1">{p.title}</span>{c.productIds.includes(p.id)&&<Check className="w-3.5 h-3.5 text-[#8C7355] shrink-0"/>}</div></button>)}</div>{c.productIds.length>0&&<button onClick={()=>{c.productIds.forEach(id=>{const p=products.find(x=>x.id===id);if(p&&p.inStock!==false)addToCart(p)});setPage('cart')}} className="mt-4 rounded-xl bg-[#F2ECE4] text-[#4E4137] px-4 py-2 text-xs font-bold">Přidat celou kolekci do košíku ({c.productIds.length})</button>}</Card>)}</div>{showCollection&&<Modal title="Nová kolekce" onClose={()=>setShowCollection(false)}><input autoFocus value={collectionName} onChange={e=>setCollectionName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&createCollection()} placeholder="Např. Nový obývák" className="w-full rounded-xl border border-[#DED3C7] px-4 py-3 text-sm"/><button onClick={createCollection} className="w-full mt-3 rounded-xl bg-[#241E1A] text-white py-3 font-bold">Vytvořit kolekci</button></Modal>}</div>}
 {tab==='addresses'&&<div className="space-y-4"><div className="flex justify-end"><button onClick={()=>setShowAddress(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#241E1A] text-white px-4 py-2.5 text-sm font-bold"><Plus className="w-4 h-4"/> Přidat adresu</button></div>{(account.addresses||[]).length===0?<Empty icon={MapPin} text="Nemáte uloženou žádnou adresu."/>:(account.addresses||[]).map(a=><Card key={a.id}><div className="flex justify-between gap-3"><div><p className="font-bold">{a.label}</p><p className="text-sm mt-2">{a.fullName}<br/>{a.street}<br/>{a.zip} {a.city}<br/>{a.country}</p>{a.phone&&<p className="text-xs text-[#897A6E] mt-2">{a.phone}</p>}</div><button onClick={()=>removeAddress(a.id)} className="text-red-500 p-1"><Trash2 className="w-4 h-4"/></button></div></Card>)}{showAddress&&<Modal title="Nová adresa" onClose={()=>setShowAddress(false)}><div className="grid sm:grid-cols-2 gap-3">{[['label','Název'],['fullName','Jméno a příjmení'],['phone','Telefon'],['street','Ulice a číslo'],['city','Město'],['zip','PSČ']].map(([k,ph])=><input key={k} value={(address as any)[k]||''} onChange={e=>setAddress({...address,[k]:e.target.value})} placeholder={ph} className="rounded-xl border border-[#DED3C7] px-4 py-3 text-sm"/>)}</div><button onClick={addAddress} className="w-full mt-3 rounded-xl bg-[#241E1A] text-white py-3 font-bold">Uložit adresu</button></Modal>}</div>}
 {tab==='benefits'&&<div className="space-y-5"><Card><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><p className="text-xs uppercase tracking-wider text-[#9A8878] font-bold">Vaše úroveň</p><h2 className="font-editorial text-3xl font-bold mt-1">{level}</h2><p className="text-sm text-[#76685D] mt-1">{points} Luvia Points</p></div><div className="w-20 h-20 rounded-full bg-[#F1E8DC] flex items-center justify-center"><Star className="w-9 h-9 text-[#8C7355]"/></div></div><div className="h-2 bg-[#EEE7DE] rounded-full mt-6 overflow-hidden"><div className="h-full bg-[#8C7355]" style={{width:`${progress}%`}}/></div><p className="text-xs text-[#897A6E] mt-2">1 bod = 10 Kč hodnoty objednávky. Body se připisují k uskutečněným objednávkám.</p></Card><div className="grid md:grid-cols-2 gap-4"><Card title="🎟️ Slevové kódy">{coupons.length?<div className="space-y-2">{coupons.map((c:any)=><div key={c.id||c.code} className="rounded-xl bg-[#F8F3ED] border border-[#E7DDD2] p-3 flex justify-between"><span className="font-mono font-bold">{c.code}</span><span className="text-xs font-bold">{c.type==='percent'?`${c.value} %`:`${c.value} Kč`}</span></div>)}</div>:<p className="text-sm text-[#897A6E]">Momentálně nemáte žádný aktivní slevový kód.</p>}</Card><Card title="🎁 Dárkové poukazy">{vouchers.length?<div className="space-y-2">{vouchers.map((v:any)=><div key={v.id||v.code} className="rounded-xl bg-[#F8F3ED] border border-[#E7DDD2] p-3 flex justify-between"><span className="font-mono font-bold">{v.code}</span><span className="text-xs font-bold">{money(v.remainingValue??v.value)}</span></div>)}</div>:<p className="text-sm text-[#897A6E]">Nemáte žádný evidovaný dárkový poukaz.</p>}</Card></div></div>}
 {tab==='profile'&&<div className="space-y-5"><Card title="Můj styl"><p className="text-sm text-[#76685D] mb-4">Vyberte, co se vám líbí. Podle toho vám budeme zobrazovat vhodnější produkty.</p><PreferenceGroup title="Styl interiéru" values={styles} selected={preferences.styles} onToggle={v=>toggle('styles',v)}/><PreferenceGroup title="Oblíbené barvy" values={colors} selected={preferences.colors} onToggle={v=>toggle('colors',v)}/><button disabled={saving} onClick={()=>save({preferences})} className="mt-5 rounded-xl bg-[#241E1A] text-white px-5 py-3 text-sm font-bold">{saving?'Ukládám…':'Uložit moje preference'}</button></Card></div>}
 {tab==='settings'&&<div className="space-y-5"><Card title="Osobní údaje"><div className="grid sm:grid-cols-2 gap-3"><input value={account.name} onChange={e=>persist({...account,name:e.target.value})} className="rounded-xl border border-[#DED3C7] px-4 py-3 text-sm" placeholder="Jméno"/><input value={account.phone||''} onChange={e=>persist({...account,phone:e.target.value})} className="rounded-xl border border-[#DED3C7] px-4 py-3 text-sm" placeholder="Telefon"/><input value={account.email} disabled className="rounded-xl border border-[#E9E2D9] bg-[#F8F5F1] px-4 py-3 text-sm text-[#8D8177]"/><button disabled={saving} onClick={()=>save({name:account.name,phone:account.phone})} className="rounded-xl bg-[#241E1A] text-white px-4 py-3 text-sm font-bold">Uložit údaje</button></div></Card><Card title="Změna hesla"><div className="grid sm:grid-cols-3 gap-3"><input type="password" value={form.currentPassword} onChange={e=>setForm({...form,currentPassword:e.target.value})} placeholder="Současné heslo" className="rounded-xl border border-[#DED3C7] px-4 py-3 text-sm"/><input type="password" value={form.newPassword} onChange={e=>setForm({...form,newPassword:e.target.value})} placeholder="Nové heslo" className="rounded-xl border border-[#DED3C7] px-4 py-3 text-sm"/><button onClick={async()=>{try{const r=await fetch('/api/customer/password',{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()},body:JSON.stringify({currentPassword:form.currentPassword,newPassword:form.newPassword})});const d=await r.json();if(!r.ok)throw new Error(d.error);addToast('success','Heslo změněno','Nové heslo bylo uloženo.');setForm({...form,currentPassword:'',newPassword:''})}catch(e:any){addToast('error','Chyba',e.message)}}} className="rounded-xl bg-[#F2ECE4] text-[#4A3C32] px-4 py-3 text-sm font-bold">Změnit heslo</button></div></Card><Card title="Účet"><p className="text-sm text-[#76685D]">Účet byl vytvořen {new Date(account.createdAt).toLocaleDateString('cs-CZ')}.</p><button onClick={logout} className="mt-4 inline-flex items-center gap-2 rounded-xl border border-red-200 text-red-600 px-4 py-2.5 text-sm font-bold"><LogOut className="w-4 h-4"/> Odhlásit se</button></Card></div>}
 </main></div></div>;
};
const Stat=({icon:Icon,title,value}:{icon:any;title:string;value:number})=><div className="bg-white rounded-2xl border border-[#E5DACD] p-4"><Icon className="w-5 h-5 text-[#8C7355]"/><p className="text-xs text-[#8C7A6A] mt-3">{title}</p><p className="font-editorial text-2xl font-bold mt-0.5">{value}</p></div>;
const Card=({title,children,action}:{title?:string;children:React.ReactNode;action?:React.ReactNode})=><section className="bg-white rounded-2xl border border-[#E5DACD] p-4 sm:p-5 shadow-sm">{(title||action)&&<div className="flex items-center justify-between gap-3 mb-4"><h2 className="font-bold text-[#2B241F]">{title}</h2>{action}</div>}{children}</section>;
const Empty=({icon:Icon,text}:{icon:any;text:string})=><div className="bg-white rounded-2xl border border-dashed border-[#DCCFC1] py-14 text-center"><Icon className="w-8 h-8 mx-auto text-[#B7A696]"/><p className="text-sm text-[#847568] mt-3">{text}</p></div>;
const MiniProduct=({product,onClick}:{product:Product;onClick:()=>void})=><button onClick={onClick} className="text-left rounded-xl overflow-hidden border border-[#E8DED4] bg-white"><img src={product.imageUrl} alt="" className="w-full aspect-square object-cover"/><div className="p-2.5"><p className="text-xs font-semibold line-clamp-2">{product.title}</p><p className="text-xs font-bold mt-1">{money(product.price)}</p></div></button>;
const PreferenceGroup=({title,values,selected,onToggle}:{title:string;values:string[];selected:string[];onToggle:(v:string)=>void})=><div className="mb-5"><p className="text-xs font-bold uppercase tracking-wider text-[#8D7A69] mb-2">{title}</p><div className="flex flex-wrap gap-2">{values.map(v=><button key={v} onClick={()=>onToggle(v)} className={`px-3 py-2 rounded-full text-xs font-semibold border transition ${selected.includes(v)?'bg-[#241E1A] text-white border-[#241E1A]':'bg-white text-[#66584D] border-[#DDD2C6]'}`}>{selected.includes(v)&&<Check className="w-3 h-3 inline mr-1"/>}{v}</button>)}</div></div>;
const Modal=({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode})=><div className="fixed inset-0 z-[80] bg-stone-950/50 backdrop-blur-sm flex items-center justify-center p-4" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><div className="bg-[#FCFAF7] rounded-3xl border border-[#E2D6CA] shadow-2xl w-full max-w-lg p-5 sm:p-6"><div className="flex items-center justify-between mb-5"><h2 className="font-editorial text-2xl font-bold">{title}</h2><button onClick={onClose} className="p-2 rounded-xl bg-[#EEE6DD]"><X className="w-4 h-4"/></button></div>{children}</div></div>;
