import React, { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Check, Heart, LogOut, MapPin, Package, Plus, RefreshCw, Settings, ShieldCheck, Sparkles, Star, Ticket, Trash2, User, WalletCards, X } from 'lucide-react';
import { useApp } from '../context/AppContext';
import type { CustomerAccount, CustomerAddress, CustomerCollection, Order, Product } from '../types';

type Tab='overview'|'orders'|'favorites'|'collections'|'addresses'|'benefits'|'profile'|'settings';
const styles=['Elegantní','Přírodní','Moderní','Minimalistický','Romantický','Rustikální'];
const colors=['Bílá','Béžová','Zlatá','Černá','Zelená','Růžová'];
const statusLabels:Record<string,string>={nova:'Objednávka přijata',zpracovava_se:'Zpracováváme',zaplaceno:'Zaplaceno',u_prepravce:'U dopravce',odeslano:'Odesláno',dokonceno:'Dokončeno',zruseno:'Zrušeno'};
const money=(n:number)=>Number(n||0).toLocaleString('cs-CZ',{minimumFractionDigits:2,maximumFractionDigits:2})+' Kč';

export const CustomerAccountPage:React.FC=()=>{
 const {products,setPage,addToCart,addToast}=useApp();
 const [account,setAccount]=useState<CustomerAccount|null>(()=>{try{return JSON.parse(localStorage.getItem('luvia_customer')||'null')}catch{return null}});
 const [token,setToken]=useState(localStorage.getItem('luvia_customer_token')||'');
 const [tab,setTab]=useState<Tab>('overview');
 const [orders,setOrders]=useState<Order[]>([]); const [vouchers,setVouchers]=useState<any[]>([]); const [coupons,setCoupons]=useState<any[]>([]);
 const [authMode,setAuthMode]=useState<'login'|'register'>('login'); const [loading,setLoading]=useState(false); const [message,setMessage]=useState('');
 const [form,setForm]=useState({name:'',email:'',phone:'',password:'',currentPassword:'',newPassword:''});
 const [address,setAddress]=useState<Partial<CustomerAddress>>({label:'Domů',fullName:'',phone:'',street:'',city:'',zip:'',country:'Česká republika'});
 const [collectionName,setCollectionName]=useState(''); const [showAddress,setShowAddress]=useState(false); const [showCollection,setShowCollection]=useState(false); const [saving,setSaving]=useState(false);
 const [preferences,setPreferences]=useState({styles:[] as string[],colors:[] as string[]});
 const headers=()=>token?{Authorization:`Bearer ${token}`}:{Authorization:''};
 const persist=(u:CustomerAccount)=>{setAccount(u);localStorage.setItem('luvia_customer',JSON.stringify(u));};
 const load=async(t=token)=>{if(!t)return;try{const r=await fetch('/api/customer/me',{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});if(!r.ok)throw new Error();const d=await r.json();persist(d.user);setPreferences(d.user.preferences||{styles:[],colors:[]});setOrders(d.orders||[]);setVouchers(d.vouchers||[]);setCoupons(d.coupons||[])}catch{localStorage.removeItem('luvia_customer');localStorage.removeItem('luvia_customer_token');setToken('');setAccount(null)}};
 useEffect(()=>{if(token)load(token)},[]);
 const auth=async()=>{setLoading(true);setMessage('');try{const endpoint=authMode==='login'?'/api/customer/login':'/api/customer/register';const body=authMode==='login'?{email:form.email,password:form.password}:{email:form.email,password:form.password,name:form.name,phone:form.phone};const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Operace se nepodařila.');localStorage.setItem('luvia_customer_token',d.token);setToken(d.token);persist(d.user);setPreferences(d.user.preferences||{styles:[],colors:[]});}catch(e:any){setMessage(e.message)}finally{setLoading(false)}};
 const save=async(updates:any)=>{setSaving(true);try{const r=await fetch('/api/customer/me',{method:'PUT',headers:{'Content-Type':'application/json',...headers()},body:JSON.stringify(updates)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Uložení se nepodařilo.');persist(d.user);setPreferences(d.user.preferences||preferences);addToast('success','Uloženo','Změny byly uloženy.')}catch(e:any){addToast('error','Chyba',e.message)}finally{setSaving(false)}};
 const logout=async()=>{await fetch('/api/customer/logout',{method:'POST',headers:headers()}).catch(()=>{});localStorage.removeItem('luvia_customer');localStorage.removeItem('luvia_customer_token');setAccount(null);setToken('');setOrders([])};
 const favoriteProducts=useMemo(()=>products.filter(p=>account?.favorites?.includes(p.id)),[products,account]);
 const points=useMemo(()=>Math.floor(orders.filter(o=>o.status!=='zruseno').reduce((s,o)=>s+Number(o.subtotal||0),0)/10),[orders]);
 const level=points>=1000?'Luvia VIP':points>=500?'Luvia Lover':points>=200?'Luvia Fan':'Začínáme';
 const next=points<200?200:points<500?500:points<1000?1000:1000; const progress=points>=1000?100:Math.min(100,Math.round(points/next*100));
 const repeat=(o:Order)=>{let n=0;o.items.forEach(i=>{const p=products.find(x=>x.id===i.productId);if(p&&p.inStock!==false){addToCart(p,i.quantity,i.customNote);n+=i.quantity}});addToast(n?'success':'error',n?'Objednávka připravena':'Nic není skladem',n?'Dostupné položky byly vloženy do košíku.':'Produkty z objednávky již nejsou dostupné.');if(n)setPage('cart')};
 const togglePref=(kind:'styles'|'colors',value:string)=>setPreferences(p=>({...p,[kind]:p[kind].includes(value)?p[kind].filter(x=>x!==value):[...p[kind],value]}));
 const addAddress=async()=>{if(!address.street||!address.city||!address.zip)return addToast('error','Doplňte adresu','Ulice, město a PSČ jsou povinné.');const a={...address,id:`addr-${Date.now()}`} as CustomerAddress;await save({addresses:[...(account?.addresses||[]),a]});setShowAddress(false)};
 const createCollection=async()=>{if(!collectionName.trim())return;const now=new Date().toISOString();const c:CustomerCollection={id:`col-${Date.now()}`,name:collectionName.trim(),productIds:[],createdAt:now,updatedAt:now};await save({collections:[...(account?.collections||[]),c]});setCollectionName('');setShowCollection(false)};
 const deleteCollection=(id:string)=>save({collections:(account?.collections||[]).filter(c=>c.id!==id)});
 const toggleCollection=async(c:CustomerCollection,pid:string)=>{const productIds=c.productIds.includes(pid)?c.productIds.filter(x=>x!==pid):[...c.productIds,pid];await save({collections:(account?.collections||[]).map(x=>x.id===c.id?{...x,productIds,updatedAt:new Date().toISOString()}:x)})};

 if(!account)return <AuthScreen mode={authMode} setMode={setAuthMode} form={form} setForm={setForm} loading={loading} message={message} onSubmit={auth}/>;

 const renderOverview=()=> <div className="space-y-5"><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3"><Stat title="Objednávky" value={orders.length} icon={Package}/><Stat title="Oblíbené" value={account.favorites.length} icon={Heart}/><Stat title="Luvia Points" value={points} icon={WalletCards}/><Stat title="Výhody" value={coupons.length+vouchers.length} icon={Ticket}/></div><Card title="Poslední objednávka">{orders.length===0?<Empty icon={Package} text="Zatím nemáte žádné objednávky."/>:<div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><b>{orders[0].orderNumber}</b><p className="text-xs text-[#897A6E] mt-1">{new Date(orders[0].createdAt).toLocaleDateString('cs-CZ')} · {statusLabels[orders[0].status]}</p><p className="font-bold mt-2">{money(orders[0].totalPrice)}</p></div><button onClick={()=>setTab('orders')} className="inline-flex items-center gap-2 text-sm font-bold text-[#8C7355]">Detail <ArrowRight className="w-4 h-4"/></button></div>}</Card><Card title="✨ Vybráno pro vás"><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{products.filter(p=>p.inStock!==false).slice(0,4).map(p=><MiniProduct key={p.id} product={p} onClick={()=>{addToCart(p);setPage('cart')}}/>)}</div></Card></div>;
 const renderOrders=()=> <div className="space-y-3">{orders.length===0?<Empty icon={Package} text="Zatím nemáte žádné objednávky."/>:orders.map(o=><Card key={o.id}><div className="flex flex-col md:flex-row md:items-center justify-between gap-4"><div><b>{o.orderNumber}</b><p className="text-xs text-[#897A6E] mt-1">{new Date(o.createdAt).toLocaleDateString('cs-CZ')} · {statusLabels[o.status]||o.status}</p><p className="font-bold mt-2">{money(o.totalPrice)}</p></div><button onClick={()=>repeat(o)} className="inline-flex items-center gap-2 rounded-xl bg-[#241E1A] text-white px-3 py-2 text-xs font-bold"><RefreshCw className="w-3.5 h-3.5"/> Objednat znovu</button></div><div className="mt-4 pt-4 border-t border-[#EEE7DF] space-y-1">{o.items.map((i,n)=><div key={n} className="flex justify-between gap-3 text-xs"><span>{i.title} × {i.quantity}</span><b>{money(i.price*i.quantity)}</b></div>)}</div></Card>)}</div>;
 const renderFavorites=()=>favoriteProducts.length===0?<Empty icon={Heart} text="Zatím nemáte žádné oblíbené produkty."/>:<div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-4">{favoriteProducts.map(p=><div key={p.id} className="bg-white rounded-2xl border border-[#E4D9CD] overflow-hidden"><img src={p.imageUrl} alt="" className="w-full aspect-square object-cover"/><div className="p-3"><p className="font-bold text-sm line-clamp-2">{p.title}</p><p className="font-bold mt-2">{money(p.price)}</p><button onClick={()=>{addToCart(p);setPage('cart')}} className="w-full mt-3 rounded-xl bg-[#241E1A] text-white py-2 text-xs font-bold">Do košíku</button></div></div>)}</div>;
 const renderCollections=()=> <div className="space-y-4"><div className="flex justify-end"><button onClick={()=>setShowCollection(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#241E1A] text-white px-4 py-2.5 text-sm font-bold"><Plus className="w-4 h-4"/> Nová kolekce</button></div>{account.collections.length===0?<Empty icon={Star} text="Vytvořte si první vlastní kolekci produktů."/>:account.collections.map(c=><Card key={c.id} title={c.name} action={<button onClick={()=>deleteCollection(c.id)} className="text-red-500"><Trash2 className="w-4 h-4"/></button>}><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{products.slice(0,8).map(p=><button key={p.id} onClick={()=>toggleCollection(c,p.id)} className={`text-left rounded-xl border overflow-hidden ${c.productIds.includes(p.id)?'border-[#8C7355] ring-2 ring-[#8C7355]/20':'border-[#E7DDD2]'}`}><img src={p.imageUrl} alt="" className="w-full aspect-square object-cover"/><div className="p-2 text-[11px] font-semibold flex justify-between gap-1"><span className="line-clamp-1">{p.title}</span>{c.productIds.includes(p.id)&&<Check className="w-3.5 h-3.5 text-[#8C7355]"/>}</div></button>)}</div>{c.productIds.length>0&&<button onClick={()=>{c.productIds.forEach(id=>{const p=products.find(x=>x.id===id);if(p&&p.inStock!==false)addToCart(p)});setPage('cart')}} className="mt-4 rounded-xl bg-[#F2ECE4] px-4 py-2 text-xs font-bold">Přidat celou kolekci do košíku ({c.productIds.length})</button>}</Card>)}</div>{showCollection&&<Modal title="Nová kolekce" onClose={()=>setShowCollection(false)}><input autoFocus value={collectionName} onChange={e=>setCollectionName(e.target.value)} placeholder="Např. Nový obývák" className="w-full rounded-xl border border-[#DED3C7] px-4 py-3 text-sm"/><button onClick={createCollection} className="w-full mt-3 rounded-xl bg-[#241E1A] text-white py-3 font-bold">Vytvořit kolekci</button></Modal>}</div>;
 const renderAddresses=()=> <div className="space-y-4"><div className="flex justify-end"><button onClick={()=>setShowAddress(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#241E1A] text-white px-4 py-2.5 text-sm font-bold"><Plus className="w-4 h-4"/> Přidat adresu</button></div>{account.addresses.length===0?<Empty icon={MapPin} text="Nemáte uloženou žádnou adresu."/>:account.addresses.map(a=><Card key={a.id}><div className="flex justify-between"><div><b>{a.label}</b><p className="text-sm mt-2">{a.fullName}<br/>{a.street}<br/>{a.zip} {a.city}<br/>{a.country}</p>{a.phone&&<p className="text-xs text-[#897A6E] mt-2">{a.phone}</p>}</div><button onClick={()=>save({addresses:account.addresses.filter(x=>x.id!==a.id)})} className="text-red-500"><Trash2 className="w-4 h-4"/></button></div></Card>)}{showAddress&&<Modal title="Nová adresa" onClose={()=>setShowAddress(false)}><div className="grid sm:grid-cols-2 gap-3">{(['label','fullName','phone','street','city','zip'] as const).map(k=><input key={k} value={(address as any)[k]||''} onChange={e=>setAddress({...address,[k]:e.target.value})} placeholder={{label:'Název',fullName:'Jméno a příjmení',phone:'Telefon',street:'Ulice a číslo',city:'Město',zip:'PSČ'}[k]} className="rounded-xl border border-[#DED3C7] px-4 py-3 text-sm"/>)}</div><button onClick={addAddress} className="w-full mt-3 rounded-xl bg-[#241E1A] text-white py-3 font-bold">Uložit adresu</button></Modal>}</div>;
 const renderBenefits=()=> <div className="space-y-5"><Card><p className="text-xs uppercase tracking-wider text-[#9A8878] font-bold">Vaše úroveň</p><h2 className="font-editorial text-3xl font-bold mt-1">{level}</h2><p className="text-sm text-[#76685D] mt-1">{points} Luvia Points</p><div className="h-2 bg-[#EEE7DE] rounded-full mt-5"><div className="h-2 bg-[#8C7355] rounded-full" style={{width:`${progress}%`}}/></div><p className="text-xs text-[#897A6E] mt-2">1 bod = 10 Kč hodnoty uskutečněných objednávek.</p></Card><div className="grid md:grid-cols-2 gap-4"><Card title="🎟️ Slevové kódy">{coupons.length?coupons.map((c:any)=><div key={c.id||c.code} className="p-3 rounded-xl bg-[#F8F3ED] mb-2 flex justify-between"><b className="font-mono">{c.code}</b><span>{c.type==='percent'?`${c.value} %`:money(c.value)}</span></div>):<p className="text-sm text-[#897A6E]">Žádný aktivní slevový kód.</p>}</Card><Card title="🎁 Dárkové poukazy">{vouchers.length?vouchers.map((v:any)=><div key={v.id||v.code} className="p-3 rounded-xl bg-[#F8F3ED] mb-2 flex justify-between"><b className="font-mono">{v.code}</b><span>{money(v.remainingValue??v.value)}</span></div>):<p className="text-sm text-[#897A6E]">Nemáte evidovaný dárkový poukaz.</p>}</Card></div></div>;
 const renderProfile=()=> <Card title="Můj styl"><p className="text-sm text-[#76685D] mb-4">Vyberte styly a barvy, které se vám líbí.</p><PreferenceGroup title="Styl interiéru" values={styles} selected={preferences.styles} onToggle={v=>togglePref('styles',v)}/><PreferenceGroup title="Oblíbené barvy" values={colors} selected={preferences.colors} onToggle={v=>togglePref('colors',v)}/><button disabled={saving} onClick={()=>save({preferences})} className="mt-3 rounded-xl bg-[#241E1A] text-white px-5 py-3 text-sm font-bold">{saving?'Ukládám…':'Uložit preference'}</button></Card>;
 const renderSettings=()=> <div className="space-y-5"><Card title="Osobní údaje"><div className="grid sm:grid-cols-2 gap-3"><input value={account.name} onChange={e=>setAccount({...account,name:e.target.value})} className="rounded-xl border border-[#DED3C7] px-4 py-3 text-sm" placeholder="Jméno"/><input value={account.phone||''} onChange={e=>setAccount({...account,phone:e.target.value})} className="rounded-xl border border-[#DED3C7] px-4 py-3 text-sm" placeholder="Telefon"/><input value={account.email} disabled className="rounded-xl border border-[#E9E2D9] bg-[#F8F5F1] px-4 py-3 text-sm"/><button onClick={()=>save({name:account.name,phone:account.phone})} className="rounded-xl bg-[#241E1A] text-white px-4 py-3 text-sm font-bold">Uložit údaje</button></div></Card><Card title="Změna hesla"><div className="grid sm:grid-cols-3 gap-3"><input type="password" value={form.currentPassword} onChange={e=>setForm({...form,currentPassword:e.target.value})} placeholder="Současné heslo" className="rounded-xl border border-[#DED3C7] px-4 py-3 text-sm"/><input type="password" value={form.newPassword} onChange={e=>setForm({...form,newPassword:e.target.value})} placeholder="Nové heslo" className="rounded-xl border border-[#DED3C7] px-4 py-3 text-sm"/><button onClick={async()=>{try{const r=await fetch('/api/customer/password',{method:'POST',headers:{'Content-Type':'application/json',...headers()},body:JSON.stringify({currentPassword:form.currentPassword,newPassword:form.newPassword})});const d=await r.json();if(!r.ok)throw new Error(d.error);addToast('success','Heslo změněno','Nové heslo bylo uloženo.');setForm({...form,currentPassword:'',newPassword:''})}catch(e:any){addToast('error','Chyba',e.message)}}} className="rounded-xl bg-[#F2ECE4] px-4 py-3 text-sm font-bold">Změnit heslo</button></div></Card><Card title="Účet"><p className="text-sm text-[#76685D]">Účet byl vytvořen {new Date(account.createdAt).toLocaleDateString('cs-CZ')}.</p><button onClick={logout} className="mt-4 inline-flex items-center gap-2 rounded-xl border border-red-200 text-red-600 px-4 py-2.5 text-sm font-bold"><LogOut className="w-4 h-4"/> Odhlásit se</button></Card></div>;
 const content=tab==='overview'?renderOverview():tab==='orders'?renderOrders():tab==='favorites'?renderFavorites():tab==='collections'?renderCollections():tab==='addresses'?renderAddresses():tab==='benefits'?renderBenefits():tab==='profile'?renderProfile():renderSettings();
 const tabs:[Tab,string,React.ElementType][]=[['overview','Přehled',Sparkles],['orders','Objednávky',Package],['favorites','Oblíbené',Heart],['collections','Moje kolekce',Star],['addresses','Adresy',MapPin],['benefits','Luvia Points',WalletCards],['profile','Můj profil',User],['settings','Nastavení',Settings]];
 return <div className="min-h-[75vh] bg-[#FCFAF7] px-4 sm:px-6 py-7 sm:py-10"><div className="max-w-7xl mx-auto flex flex-col lg:flex-row gap-6"><aside className="lg:w-64 shrink-0"><div className="bg-[#241E1A] text-[#FAF7F2] rounded-3xl p-5 shadow-lg"><div className="flex items-center gap-3 mb-5"><div className="w-11 h-11 rounded-2xl bg-[#8C7355] flex items-center justify-center font-bold text-lg">{account.name.slice(0,1).toUpperCase()}</div><div className="min-w-0"><p className="font-bold truncate">{account.name}</p><p className="text-[11px] text-[#CDBEAF] truncate">{account.email}</p></div></div><div className="rounded-2xl bg-white/10 p-3 mb-4"><div className="flex justify-between text-xs"><span>{level}</span><span>{points} bodů</span></div><div className="h-1.5 bg-white/10 rounded-full mt-2"><div className="h-full bg-[#C5A880] rounded-full" style={{width:`${progress}%`}}/></div></div><div className="space-y-1">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-left text-sm ${tab===id?'bg-white text-[#241E1A] font-bold':'text-[#D9CDC0] hover:bg-white/10'}`}><Icon className="w-4 h-4"/>{label}</button>)}</div><button onClick={logout} className="w-full mt-4 pt-4 border-t border-white/10 flex items-center gap-3 px-3 py-2.5 text-sm text-[#D9CDC0]"><LogOut className="w-4 h-4"/> Odhlásit se</button></div></aside><main className="flex-1 min-w-0"><div className="flex items-center justify-between mb-6"><div><p className="text-[11px] uppercase tracking-[0.2em] text-[#9A8878] font-bold">Můj Luvia</p><h1 className="font-editorial text-3xl sm:text-4xl font-bold">{tabs.find(t=>t[0]===tab)?.[1]}</h1></div><button onClick={()=>load()} className="p-2.5 rounded-xl border border-[#E0D6CA] bg-white text-[#8C7355]"><RefreshCw className="w-4 h-4"/></button></div>{content}</main></div>{showAddress&&null}</div>;
};

const AuthScreen=({mode,setMode,form,setForm,loading,message,onSubmit}:{mode:'login'|'register';setMode:(m:'login'|'register')=>void;form:any;setForm:(f:any)=>void;loading:boolean;message:string;onSubmit:()=>void})=><div className="min-h-[70vh] px-4 py-12 bg-[#FCFAF7]"><div className="max-w-md mx-auto bg-white rounded-3xl border border-[#E5DACD] shadow-xl p-6 sm:p-8"><div className="text-center mb-7"><div className="mx-auto w-14 h-14 rounded-2xl bg-[#F2E9DE] flex items-center justify-center text-[#8C7355]"><User className="w-7 h-7"/></div><h1 className="font-editorial text-3xl font-bold mt-4">{mode==='login'?'Vítejte zpět':'Vytvořte si účet'}</h1><p className="text-sm text-[#76685D] mt-2">{mode==='login'?'Přihlaste se do svého osobního prostoru Luvia Decor.':'Objednávky, oblíbené, adresy, kolekce a Luvia Points na jednom místě.'}</p></div><div className="space-y-3">{mode==='register'&&<><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Jméno a příjmení" className="w-full rounded-xl border border-[#DED3C7] px-4 py-3 text-sm"/><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Telefon" className="w-full rounded-xl border border-[#DED3C7] px-4 py-3 text-sm"/></>}<input value={form.email} onChange={e=>setForm({...form,email:e.target.value})} type="email" placeholder="E-mail" className="w-full rounded-xl border border-[#DED3C7] px-4 py-3 text-sm"/><input value={form.password} onChange={e=>setForm({...form,password:e.target.value})} type="password" placeholder="Heslo (min. 8 znaků)" className="w-full rounded-xl border border-[#DED3C7] px-4 py-3 text-sm"/>{message&&<div className="rounded-xl bg-red-50 border border-red-100 text-red-700 px-4 py-3 text-xs">{message}</div>}<button disabled={loading} onClick={onSubmit} className="w-full rounded-xl bg-[#241E1A] text-white py-3.5 font-bold disabled:opacity-60">{loading?'Pracuji…':mode==='login'?'Přihlásit se':'Vytvořit účet'}</button></div><div className="text-center mt-5 text-sm text-[#76685D]">{mode==='login'?'Nemáte účet?':'Už máte účet?'} <button onClick={()=>{setMode(mode==='login'?'register':'login');setForm({...form,password:''})}} className="font-bold text-[#8C7355] underline">{mode==='login'?'Vytvořit účet':'Přihlásit se'}</button></div><div className="mt-6 pt-5 border-t border-[#EEE6DD] text-center text-[11px] text-[#95877A]"><ShieldCheck className="w-3.5 h-3.5 inline mr-1"/> Heslo je ukládáno zabezpečeně.</div></div></div>;

const Stat=({icon:Icon,title,value}:{icon:any;title:string;value:number})=><div className="bg-white rounded-2xl border border-[#E5DACD] p-4"><Icon className="w-5 h-5 text-[#8C7355]"/><p className="text-xs text-[#8C7A6A] mt-3">{title}</p><p className="font-editorial text-2xl font-bold">{value}</p></div>;
const Card=({title,children,action}:{title?:string;children:React.ReactNode;action?:React.ReactNode})=><section className="bg-white rounded-2xl border border-[#E5DACD] p-4 sm:p-5 shadow-sm">{(title||action)&&<div className="flex items-center justify-between gap-3 mb-4"><h2 className="font-bold">{title}</h2>{action}</div>}{children}</section>;
const Empty=({icon:Icon,text}:{icon:any;text:string})=><div className="bg-white rounded-2xl border border-dashed border-[#DCCFC1] py-14 text-center"><Icon className="w-8 h-8 mx-auto text-[#B7A696]"/><p className="text-sm text-[#847568] mt-3">{text}</p></div>;
const MiniProduct=({product,onClick}:{product:Product;onClick:()=>void})=><button onClick={onClick} className="text-left rounded-xl overflow-hidden border border-[#E8DED4] bg-white"><img src={product.imageUrl} alt="" className="w-full aspect-square object-cover"/><div className="p-2.5"><p className="text-xs font-semibold line-clamp-2">{product.title}</p><p className="text-xs font-bold mt-1">{money(product.price)}</p></div></button>;
const PreferenceGroup=({title,values,selected,onToggle}:{title:string;values:string[];selected:string[];onToggle:(v:string)=>void})=><div className="mb-5"><p className="text-xs font-bold uppercase tracking-wider text-[#8D7A69] mb-2">{title}</p><div className="flex flex-wrap gap-2">{values.map(v=><button key={v} onClick={()=>onToggle(v)} className={`px-3 py-2 rounded-full text-xs font-semibold border ${selected.includes(v)?'bg-[#241E1A] text-white border-[#241E1A]':'bg-white text-[#66584D] border-[#DDD2C6]'}`}>{selected.includes(v)&&<Check className="w-3 h-3 inline mr-1"/>}{v}</button>)}</div></div>;
const Modal=({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode})=><div className="fixed inset-0 z-[80] bg-stone-950/50 flex items-center justify-center p-4"><div className="bg-[#FCFAF7] rounded-3xl border border-[#E2D6CA] shadow-2xl w-full max-w-lg p-5 sm:p-6"><div className="flex items-center justify-between mb-5"><h2 className="font-editorial text-2xl font-bold">{title}</h2><button onClick={onClose} className="p-2 rounded-xl bg-[#EEE6DD]"><X className="w-4 h-4"/></button></div>{children}</div></div>;
