import React from 'react';
import { ArrowLeft, ShieldCheck } from 'lucide-react';
import { useApp } from '../context/AppContext';

const sections = [
  ['1. Správce osobních údajů', `Správcem osobních údajů je Ladislav Pekárek / Luvia Decor, IČO: 29905061, se sídlem U Rejdiště 3732/15, 767 01 Kroměříž, Česká republika.\n\nE-mail: podpora@luvia-decor.cz\nTelefon: +420 702 345 999\nWeb: www.luvia-decor.cz`],
  ['2. Jaké osobní údaje zpracováváme', `V souvislosti s provozem e-shopu můžeme zpracovávat zejména jméno a příjmení, e-mail, telefonní číslo, doručovací nebo fakturační adresu, údaje o objednávce, způsobu dopravy a platby, poznámku k objednávce a komunikaci se zákazníkem.\n\nU osobního odběru zpracováváme pouze údaje potřebné k identifikaci a předání objednávky.`],
  ['3. Účely a právní základy zpracování', `Osobní údaje zpracováváme zejména za účelem přijetí, zpracování a splnění objednávky, komunikace se zákazníkem, doručení nebo předání zboží, řešení reklamací a odstoupení od smlouvy a plnění účetních, daňových a dalších zákonných povinností.\n\nPrávním základem je zejména plnění smlouvy nebo provedení opatření před jejím uzavřením, splnění právní povinnosti a v odůvodněných případech oprávněný zájem správce. Pokud budeme pro konkrétní účel potřebovat souhlas, vyžádáme si jej samostatně a dobrovolně.`],
  ['4. Objednávky a zákaznická komunikace', `Údaje uvedené v objednávce používáme k jejímu vyřízení a k nezbytné komunikaci, například k potvrzení objednávky, informování o změně jejího stavu, doručení nebo platbě.\n\nSouhlas se zpracováním osobních údajů není podmínkou nákupu. Pro běžné vyřízení objednávky je právním základem zejména smlouva a zákonné povinnosti.`],
  ['5. Platby a doprava', `Při bankovním převodu jsou zákazníkovi předány platební údaje potřebné k úhradě objednávky. Údaje potřebné pro doručení mohou být předány příslušnému dopravci nebo poskytovateli výdejních míst v rozsahu nezbytném pro doručení zásilky.\n\nAktuálně e-shop nabízí bankovní převod a dopravu prostřednictvím dostupných přepravců uvedených při objednávce.`],
  ['6. E-mailová komunikace', `E-mail zákazníka používáme pro komunikaci související s objednávkou, včetně potvrzení objednávky a informací o jejím stavu. Tyto zprávy jsou součástí vyřízení smluvního vztahu a nejde o marketingový souhlas.`],
  ['7. Doba uchování', `Osobní údaje uchováváme pouze po dobu nezbytnou pro příslušný účel. Údaje související s objednávkami a účetními či daňovými doklady uchováváme po dobu stanovenou právními předpisy. Údaje zpracovávané pouze na základě souhlasu uchováváme do jeho odvolání nebo po dobu uvedenou při jeho udělení, pokud právní předpis nestanoví jinak.`],
  ['8. Komu mohou být údaje zpřístupněny', `Údaje mohou být v nezbytném rozsahu zpřístupněny poskytovatelům hostingu, databázových a IT služeb, e-mailových služeb, účetních služeb a dopravcům či poskytovatelům výdejních míst. Tito příjemci mohou vystupovat jako zpracovatelé osobních údajů nebo samostatní správci podle povahy konkrétní služby.`],
  ['9. Cookies', `Web může používat technické cookies a obdobné technologie nezbytné pro jeho správné fungování, například pro košík, zabezpečení a základní provoz. Pro netechnické analytické nebo marketingové cookies je vyžadován příslušný souhlas, pokud jsou na webu používány. Nastavení cookies lze spravovat prostřednictvím dostupných funkcí webu.`],
  ['10. Práva zákazníka', `Za podmínek stanovených právními předpisy máte právo požadovat přístup ke svým osobním údajům, jejich opravu, výmaz, omezení zpracování, přenositelnost údajů a vznést námitku proti zpracování založenému na oprávněném zájmu. Pokud je zpracování založeno na souhlasu, můžete jej kdykoli odvolat. Odvoláním souhlasu není dotčena zákonnost zpracování provedeného před jeho odvoláním.`],
  ['11. Jak uplatnit práva', `Své požadavky můžete zaslat na e-mail podpora@luvia-decor.cz nebo písemně na adresu sídla správce. V žádosti uveďte, čeho se požadavek týká. V případě důvodných pochybností můžeme požádat o přiměřené ověření totožnosti, aby nedošlo k neoprávněnému zpřístupnění údajů.`],
  ['12. Právo podat stížnost', `Pokud se domníváte, že při zpracování osobních údajů dochází k porušení právních předpisů, máte právo podat stížnost u Úřadu pro ochranu osobních údajů.`],
  ['13. Zabezpečení', `Přijímáme přiměřená technická a organizační opatření k ochraně osobních údajů před neoprávněným přístupem, změnou, ztrátou nebo zničením. Přístup k údajům je omezen podle potřeby a používané systémy jsou chráněny odpovídajícími bezpečnostními mechanismy.`],
  ['14. Aktualizace zásad', `Tyto zásady mohou být aktualizovány zejména při změně právních předpisů, používaných technologií nebo způsobu provozu e-shopu. Aktuální znění je vždy zveřejněno na této stránce.`],
];

export const PrivacyPage: React.FC = () => {
  const { setPage } = useApp();
  return <div className="bg-[#FAF8F5] py-10 sm:py-14"><div className="max-w-4xl mx-auto px-4 sm:px-6"><button type="button" onClick={() => setPage('home')} className="flex items-center gap-2 text-sm text-[#85786E] mb-8"><ArrowLeft className="w-4 h-4"/> Zpět</button><div className="bg-white rounded-[2rem] border border-[#E6DDD3] shadow-sm overflow-hidden"><div className="p-7 sm:p-10 border-b border-[#EEE7DE] bg-[#FBF7F1]"><div className="flex items-center gap-3 text-[#9A7B58] mb-3"><ShieldCheck className="w-6 h-6"/><span className="text-xs uppercase tracking-[.2em] font-bold">Luvia Decor · GDPR</span></div><h1 className="font-editorial text-3xl sm:text-5xl font-bold">Ochrana osobních údajů</h1><p className="mt-3 text-sm text-[#746960] leading-relaxed">Informace o zpracování osobních údajů podle obecného nařízení GDPR a souvisejících právních předpisů.</p></div><div className="p-7 sm:p-10 space-y-8">{sections.map(([title,text]) => <section key={title}><h2 className="font-editorial text-xl sm:text-2xl font-bold mb-3">{title}</h2><div className="whitespace-pre-line text-sm leading-7 text-[#554B44]">{text}</div></section>)}<p className="pt-5 border-t border-[#EEE7DE] text-xs text-[#8B8178]">Poslední aktualizace: 5. 9. 2026</p></div></div></div></div>;
};
