import React, { useState } from 'react';
import { CheckCircle2, Minus, Plus, Trash2, ArrowLeft, Truck, CreditCard, User, MapPinned, PackageCheck, MapPin } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { DpdPickupWidget } from '../components/DpdPickupWidget';

const SHIPPING = { DPD: { address: 105, pickup_point: 75 }, 'Zásilkovna': { address: 89, pickup_point: 62 } };
type Method = 'address' | 'pickup_point' | 'personal_pickup';
const bankIban = 'CZ45550000000000963625011';
const qr = (order: any) => { const number = String(order?.orderNumber || order?.id || ''); const vs = number.replace(/\D/g, ''); const amount = Number(order?.totalPrice || 0).toFixed(2); const payload = `SPD*1.0*ACC:${bankIban}*AM:${amount}*CC:CZK*X-VS:${vs}*X-MSG:${number}`; return `https://api.qrserver.com/v1/create-qr-code/?size=260x260&margin=8&data=${encodeURIComponent(payload)}`; };

const inputClass = 'w-full rounded-2xl border border-[#E5DCD2] bg-[#FCFAF7] px-4 py-3.5 text-sm text-[#302923] outline-none transition focus:border-[#9A7B58] focus:bg-white focus:ring-4 focus:ring-[#9A7B58]/10 placeholder:text-[#A79C91]';
const optionClass = (active:boolean) => `relative rounded-2xl border p-4 text-left transition-all duration-200 ${active ? 'border-[#9A7B58] bg-[#FBF6EF] shadow-[0_10px_28px_rgba(80,60,40,.09)]' : 'border-[#E8E0D8] bg-white hover:border-[#C8B39B] hover:-translate-y-0.5'}`;

export const StableCartPage: React.FC = () => {
 const { cart, cartTotal, removeFromCart, updateCartQuantity, clearCart, setPage, addToast } = useApp();
 const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [phone,setPhone]=useState(''); const [street,setStreet]=useState(''); const [city,setCity]=useState(''); const [zip,setZip]=useState(''); const [note,setNote]=useState('');
 const [carrier,setCarrier]=useState<'DPD'|'Zásilkovna'>('DPD'); const [method,setMethod]=useState<Method>('address'); const [point,setPoint]=useState<any>(null); const [picker,setPicker]=useState(false); const [sending,setSending]=useState(false); const [done,setDone]=useState<any>(null);
 const shipping=method==='personal_pickup'?0:SHIPPING[carrier][method]; const total=cartTotal+shipping;
 const selectMethod=(m:Method)=>{ setMethod(m); setPoint(null); if(m==='pickup_point') setPicker(true); };
 const selectCarrier=(c:'DPD'|'Zásilkovna')=>{ setCarrier(c); setMethod('address'); setPoint(null); };
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!cart.length)return addToast('error','Košík je prázdný','Přidejte nejprve produkt.');if(!name.trim()||!email.trim()||!phone.trim())return addToast('error','Chybí údaje','Vyplňte jméno, e-mail a telefon.');if(method==='address'&&(!street.trim()||!city.trim()||!zip.trim()))return addToast('error','Chybí adresa','Vyplňte ulici, město a PSČ.');if(method==='pickup_point'&&!point)return addToast('error','Vyberte místo','Vyberte výdejní místo nebo box na mapě.');setSending(true);try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer:{fullName:name.trim(),email:email.trim(),phone:phone.trim(),street:method==='personal_pickup'?'':street.trim(),city:method==='personal_pickup'?'':city.trim(),zip:method==='personal_pickup'?'':zip.trim(),country:'Česká republika',note:note.trim()},items:cart.map(i=>({productId:i.product.id,title:i.product.title,price:i.product.price,quantity:i.quantity,category:i.product.category,imageUrl:i.product.imageUrl,customNote:i.customNote})),paymentMethod:'bank_transfer',delivery:method==='personal_pickup'?{method:'personal_pickup'}:{method,carrier,pickupPoint:point?String(point.name||point.address||point.id||'Vybrané místo'):undefined}})});const d=await r.json();if(!r.ok||!d.order)throw new Error(d.error||'Objednávku se nepodařilo odeslat.');setDone(d.order);clearCart();addToast('success','Objednávka přijata','Objednávka byla úspěšně odeslána.')}catch(err:any){addToast('error','Chyba při odesílání',err?.message||'Zkuste to znovu.')}finally{setSending(false)}};
 if(done){const vs=String(done.orderNumber||done.id||'').replace(/\D/g,'');return <div className="min-h-[70vh] flex items-center justify-center px-4 py-14 bg-[#FAF8F5]"><div className="w-full max-w-3xl bg-white rounded-[2rem] border border-[#E6DDD3] shadow-[0_24px_70px_rgba(50,40,30,.10)] p-7 sm:p-12 text-center"><div className="w-16 h-16 mx-auto rounded-full bg-[#F4EEE5] flex items-center justify-center mb-5"><CheckCircle2 className="w-8 h-8 text-[#806746]"/></div><p className="text-[11px] uppercase tracking-[.22em] text-[#9A7B58]">Číslo objednávky · {done.orderNumber}</p><h1 className="font-editorial text-3xl sm:text-4xl font-bold mt-3 text-[#302923]">Objednávka byla přijata</h1><p className="text-sm text-[#7B7067] mt-3">Děkujeme za Váš nákup. Pro dokončení objednávky proveďte bankovní převod.</p><div className="mt-8 rounded-2xl bg-[#FAF7F2] border border-[#E9E0D6] p-5 sm:p-6 text-left space-y-3 text-sm"><p><b>Číslo účtu:</b> 963625011/5500</p><p><b>IBAN:</b> CZ45 5500 0000 0096 3625 011</p><p><b>Variabilní symbol:</b> {vs}</p><p><b>Částka:</b> {Number(done.totalPrice||0).toLocaleString('cs-CZ')} Kč</p><p><b>Poznámka pro příjemce:</b> {done.orderNumber}</p></div><div className="mt-7 flex justify-center"><img src={qr(done)} alt="QR platba" width="260" height="260" className="max-w-full rounded-2xl border border-[#E3D8CA] shadow-sm"/></div><p className="mt-4 text-xs text-[#8B8178]">QR platba obsahuje číslo objednávky také jako poznámku pro příjemce.</p><button type="button" onClick={()=>setPage('home')} className="mt-8 px-7 py-3.5 rounded-2xl bg-[#302923] text-white text-sm font-semibold hover:bg-[#463C35] transition">Zpět na úvod</button></div></div>}
 if(!cart.length)return <div className="max-w-3xl mx-auto px-4 py-20 text-center"><div className="w-16 h-16 mx-auto rounded-full bg-[#F4EEE5] flex items-center justify-center"><PackageCheck className="w-7 h-7 text-[#806746]"/></div><h1 className="font-editorial text-4xl font-bold text-[#302923] mt-5">Košík je prázdný</h1><p className="mt-3 text-[#7B7067]">Vyberte si něco krásného z naší nabídky.</p><button onClick={()=>setPage('catalog')} className="mt-7 px-7 py-3.5 rounded-2xl bg-[#302923] text-white font-semibold">Prohlédnout produkty</button></div>;
 return <div className="relative overflow-hidden bg-[#FAF8F5] py-8 sm:py-12 lg:py-14"><div className="pointer-events-none absolute -top-32 -right-32 h-72 w-72 rounded-full bg-[#EDE1D2]/50 blur-3xl"/><div className="pointer-events-none absolute top-96 -left-40 h-80 w-80 rounded-full bg-[#EFE7DE]/60 blur-3xl"/><div className="relative max-w-6xl mx-auto px-4 sm:px-6 lg:px-8"><button type="button" onClick={()=>setPage('catalog')} className="group flex items-center gap-2 text-sm text-[#85786E] hover:text-[#302923] transition mb-7"><ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition"/> Zpět do nabídky</button><div className="mb-8 sm:mb-10"><p className="text-[10px] sm:text-[11px] uppercase tracking-[.28em] text-[#9A7B58] font-bold">Luvia Decor · bezpečná objednávka</p><h1 className="font-editorial text-4xl sm:text-5xl lg:text-6xl font-bold text-[#302923] mt-2">Váš košík</h1><p className="mt-3 max-w-2xl text-sm sm:text-base text-[#85786E] leading-relaxed">Elegantní dokončení objednávky. Vyberte dopravu, místo převzetí a doplňte své kontaktní údaje.</p></div>
 <div className="grid lg:grid-cols-[1fr_430px] gap-6 lg:gap-8 items-start"><section className="space-y-5"><div className="bg-white/95 backdrop-blur rounded-[1.75rem] border border-[#E6DDD3] shadow-[0_16px_50px_rgba(50,40,30,.065)] overflow-hidden"><div className="px-5 sm:px-7 py-5 border-b border-[#EEE7DE] flex justify-between items-center"><div><p className="text-[10px] uppercase tracking-[.2em] text-[#9A7B58] font-bold">01</p><h2 className="font-editorial text-2xl sm:text-3xl font-bold text-[#302923]">Vaše produkty</h2></div><span className="rounded-full bg-[#F5EFE8] px-3 py-1.5 text-xs font-semibold text-[#786A5E]">{cart.reduce((s,i)=>s+i.quantity,0)} ks</span></div><div className="p-4 sm:p-7 space-y-3">{cart.map(i=><div key={i.product.id} className="group rounded-2xl border border-[#EEE7DE] bg-[#FCFAF7] p-3 sm:p-4 flex gap-3 sm:gap-4 items-center hover:bg-white hover:shadow-sm transition"><div className="w-20 h-20 sm:w-24 sm:h-24 rounded-xl bg-[#F3EEE8] overflow-hidden shrink-0">{i.product.imageUrl?<img src={i.product.imageUrl} alt="" className="w-full h-full object-cover"/>:<div className="w-full h-full flex items-center justify-center text-[#B4A99E]"><PackageCheck className="w-6 h-6"/></div>}</div><div className="min-w-0 flex-1"><div className="font-semibold text-[#302923] break-words">{i.product.title}</div><div className="text-sm text-[#9A7B58] mt-1">{Number(i.product.price).toLocaleString('cs-CZ')} Kč / ks</div><div className="mt-3 inline-flex items-center rounded-xl border border-[#E4DBD1] bg-white overflow-hidden"><button type="button" aria-label="Snížit množství" onClick={()=>updateCartQuantity(i.product.id,i.quantity-1)} className="w-9 h-9 flex items-center justify-center text-[#6F645C] hover:bg-[#F4EEE8]"><Minus className="w-3.5 h-3.5"/></button><span className="w-9 text-center text-sm font-semibold">{i.quantity}</span><button type="button" aria-label="Zvýšit množství" onClick={()=>updateCartQuantity(i.product.id,i.quantity+1)} className="w-9 h-9 flex items-center justify-center text-[#6F645C] hover:bg-[#F4EEE8]"><Plus className="w-3.5 h-3.5"/></button></div></div><div className="text-right self-stretch flex flex-col items-end justify-between shrink-0"><button type="button" aria-label="Odstranit produkt" onClick={()=>removeFromCart(i.product.id)} className="p-2 rounded-xl text-[#A59A91] hover:text-rose-600 hover:bg-rose-50 transition"><Trash2 className="w-4 h-4"/></button><div className="font-semibold text-sm sm:text-base text-[#302923]">{(Number(i.product.price)*i.quantity).toLocaleString('cs-CZ')} Kč</div></div></div>)}</div></div></section>
 <form onSubmit={submit} className="bg-white/95 backdrop-blur rounded-[1.75rem] border border-[#E6DDD3] shadow-[0_16px_50px_rgba(50,40,30,.075)] p-5 sm:p-7 space-y-6 lg:sticky lg:top-6"><div><p className="text-[10px] uppercase tracking-[.2em] text-[#9A7B58] font-bold">02 · 03 · 04</p><h2 className="font-editorial text-2xl sm:text-3xl font-bold mt-1 text-[#302923]">Dokončení objednávky</h2></div><div><div className="flex items-center gap-2 mb-3"><User className="w-4 h-4 text-[#9A7B58]"/><h3 className="font-semibold text-[#302923]">Kontaktní údaje</h3></div><div className="space-y-3"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Jméno a příjmení" className={inputClass}/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="E-mail" className={inputClass}/><input required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Telefon" className={inputClass}/></div></div>
 <div><div className="flex items-center gap-2 mb-3"><Truck className="w-4 h-4 text-[#9A7B58]"/><h3 className="font-semibold text-[#302923]">Doprava</h3></div><div className="grid grid-cols-2 gap-2">{(['DPD','Zásilkovna'] as const).map(c=><button type="button" key={c} onClick={()=>selectCarrier(c)} className={optionClass(carrier===c)}><span className="font-semibold text-[#302923]">{c}</span><span className="block text-[11px] text-[#8B8178] mt-1">Doručení na adresu nebo výdejní místo</span>{carrier===c&&<span className="absolute top-3 right-3 w-2 h-2 rounded-full bg-[#9A7B58]"/>}</button>)}</div></div>
 <div><div className="flex items-center gap-2 mb-3"><MapPinned className="w-4 h-4 text-[#9A7B58]"/><h3 className="font-semibold text-[#302923]">Způsob doručení</h3></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-2">{([['address','Na adresu','Doručení kurýrem'],['pickup_point','Výdejní místo','Výdejní místo nebo BOX'],['personal_pickup','Osobní odběr Kroměříž','Převzetí v ateliéru']] as [Method,string,string][]).map(([m,l,d])=><button type="button" key={m} onClick={()=>selectMethod(m)} className={optionClass(method===m)}><span className="font-semibold text-sm text-[#302923]">{l}</span><span className="block text-[10px] text-[#8B8178] mt-1">{d}</span>{method===m&&<span className="absolute top-3 right-3 w-2 h-2 rounded-full bg-[#9A7B58]"/>}</button>)}</div></div>
 {method==='address'&&<div className="space-y-3"><input required value={street} onChange={e=>setStreet(e.target.value)} placeholder="Ulice a číslo domu" className={inputClass}/><div className="grid grid-cols-1 sm:grid-cols-2 gap-2"><input required value={city} onChange={e=>setCity(e.target.value)} placeholder="Město" className={inputClass}/><input required value={zip} onChange={e=>setZip(e.target.value)} placeholder="PSČ" className={inputClass}/></div></div>}
 {method==='pickup_point'&&<div className="rounded-2xl border border-[#DCCDBB] bg-[#FBF6EF] p-4"><div className="flex items-start gap-3"><div className="mt-0.5 rounded-xl bg-white p-2 text-[#9A7B58] shadow-sm"><MapPin className="w-4 h-4"/></div><div className="min-w-0 flex-1"><p className="font-semibold text-sm text-[#302923]">Výdejní místo nebo BOX</p><p className="text-xs text-[#7B7067] mt-1 leading-relaxed">Mapa se otevře <b>automaticky</b> po kliknutí na tuto možnost. BOX je součástí výdejních míst.</p>{point&&<div className="mt-3 rounded-xl bg-white border border-[#E8DDD1] p-3 text-xs text-[#6F645C]">Vybrané místo: <b className="text-[#302923] break-words">{String(point.name||point.address||point.id||'Vybrané místo')}</b></div>}</div></div></div>}
 {picker&&<DpdPickupWidget initialCarrier={carrier} onSelect={p=>{setPoint(p);setPicker(false)}}/>}
 <textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Poznámka k objednávce (nepovinné)" className={`${inputClass} min-h-24 resize-y`}/>
 <div className="rounded-2xl bg-[#F8F4EE] border border-[#E9E0D6] p-4"><div className="flex items-center gap-2 text-sm font-semibold mb-3"><CreditCard className="w-4 h-4 text-[#9A7B58]"/>Platba</div><div className="flex justify-between gap-4 text-sm"><span className="text-[#7B7067]">Bankovní převod</span><span className="font-medium text-right">Po odeslání objednávky</span></div></div>
 <div className="border-t border-[#EEE7DE] pt-5 space-y-2"><div className="flex justify-between text-sm"><span className="text-[#7B7067]">Zboží</span><b>{cartTotal.toLocaleString('cs-CZ')} Kč</b></div><div className="flex justify-between text-sm"><span className="text-[#7B7067]">Doprava</span><b>{shipping.toLocaleString('cs-CZ')} Kč</b></div><div className="flex justify-between items-end gap-4 pt-2"><span className="font-editorial text-xl font-bold text-[#302923]">Celkem</span><b className="text-2xl text-[#302923] whitespace-nowrap">{total.toLocaleString('cs-CZ')} Kč</b></div></div>
 <button type="submit" disabled={sending} className="w-full rounded-2xl bg-[#302923] text-white py-4 font-semibold tracking-wide shadow-[0_10px_25px_rgba(48,41,35,.18)] hover:bg-[#463C35] hover:-translate-y-0.5 transition disabled:opacity-50 disabled:hover:translate-y-0">{sending?'Odesílám objednávku…':'Odeslat objednávku'}</button><p className="text-[10px] leading-relaxed text-center text-[#9A8F86]">Odesláním objednávky souhlasíte s obchodními podmínkami Luvia Decor.</p></form></div></div></div>;
};
