import React from 'react';

export const CustomerAccountTermsSection:React.FC=()=> <section className="max-w-4xl mx-auto px-4 sm:px-6 pb-10"><div className="rounded-3xl border border-[#E4D8CB] bg-white p-5 sm:p-7 shadow-sm"><p className="text-[11px] uppercase tracking-[0.2em] text-[#8C7355] font-bold mb-2">Doplnění obchodních podmínek</p><h2 className="font-editorial text-2xl sm:text-3xl font-bold text-[#241E1A]">Zákaznický účet „Můj Luvia“</h2><div className="mt-5 space-y-5 text-sm leading-7 text-[#55483E]">
<p><strong>1. Zřízení účtu.</strong> Zákaznický účet je dobrovolná funkce e-shopu Luvia Decor. Zákazník může nakupovat i bez registrace. Účet lze vytvořit prostřednictvím funkce „Můj Luvia“ zadáním jména, e-mailu, případně telefonu a hesla. Pro bezpečnost účtu musí heslo obsahovat alespoň 8 znaků. Jeden e-mail lze použít pouze pro jeden zákaznický účet.</p>
<p><strong>2. Přihlášení a používání účtu.</strong> Po registraci se zákazník přihlásí e-mailem a heslem. Po úspěšném přihlášení získá přístup k osobnímu dashboardu, ve kterém může spravovat své údaje, adresy, oblíbené produkty, vlastní kolekce, preference a další funkce účtu. Přihlášení lze kdykoli ukončit funkcí „Odhlásit se“.</p>
<p><strong>3. Objednávky a historie.</strong> Objednávky spojené s e-mailovou adresou zákaznického účtu se zobrazují v části „Objednávky“. Zákazník zde může vidět číslo objednávky, datum, položky, cenu a aktuální stav. U dostupných produktů lze použít funkci „Objednat znovu“, která vloží dostupné položky z vybrané objednávky do košíku. Tímto vložením ještě nevzniká nová objednávka; ta vzniká až standardním dokončením objednávkového procesu.</p>
<p><strong>4. Oblíbené produkty.</strong> Zákazník může ukládat produkty do seznamu oblíbených. Oblíbené položky slouží pouze jako osobní pomůcka a jejich uložení nezajišťuje rezervaci, dostupnost ani cenu produktu.</p>
<p><strong>5. Moje Luvia kolekce.</strong> Zákazník může vytvářet vlastní kolekce produktů, pojmenovávat je, přidávat do nich produkty a následně dostupné položky celé kolekce vložit do košíku. Kolekce nepředstavuje rezervaci zboží ani závaznou objednávku. Zákazník odpovídá za obsah a názvy svých vlastních kolekcí.</p>
<p><strong>6. Adresy.</strong> V účtu lze uložit doručovací adresy pro rychlejší vyplnění objednávky. Uložená adresa sama o sobě neznamená, že bude použita při každé další objednávce. Před odesláním objednávky je zákazník povinen zkontrolovat správnost aktuálně použitých údajů.</p>
<p><strong>7. Můj profil a preference.</strong> Zákazník si může nastavit oblíbený styl interiéru a barvy. Tyto preference slouží k personalizaci obsahu účtu a doporučení produktů. Nejde o povinné údaje a jejich nevyplnění nemá vliv na možnost nákupu.</p>
<p><strong>8. Dárkové poukazy a slevové kódy.</strong> V účtu mohou být zobrazeny aktivní dárkové poukazy nebo slevové kódy, které jsou k účtu nebo zákazníkovi přiřazeny či jsou pro něj dostupné. U každého benefitu mohou platit vlastní podmínky, doba platnosti, hodnota nebo omezení. Zobrazení v účtu samo o sobě nemění podmínky konkrétního poukazu nebo slevového kódu.</p>
<p><strong>9. Luvia Points a úrovně.</strong> Program Luvia Points je věrnostní funkce účtu. Zákazník získává <strong>1 bod za každých 50 Kč hodnoty uskutečněných objednávek</strong>, přičemž zrušené objednávky se do výpočtu nezapočítávají. Body nejsou penězi, nelze je směnit za hotovost a jejich použití se řídí aktuálními pravidly programu. Úrovně účtu jsou „Začínáme“, „Luvia Fan“, „Luvia Lover“ a „Luvia VIP“; hranice a případné výhody mohou být Luvia Decor přiměřeně změněny pro budoucí období. Změna programu nemá zpětně rušit již řádně připsané nároky bez právního důvodu.</p>
<p><strong>10. Bezpečnost účtu.</strong> Zákazník je povinen chránit své přihlašovací údaje a nesdělovat heslo třetím osobám. Pokud má podezření na neoprávněný přístup, má bez zbytečného odkladu změnit heslo a kontaktovat Luvia Decor. Luvia Decor nebude zákazníka žádat o zaslání hesla e-mailem ani telefonicky.</p>
<p><strong>11. Změna údajů a hesla.</strong> Zákazník může své jméno, telefon, adresy, preference a další dostupné údaje upravovat přímo v účtu. Heslo lze změnit po ověření současného hesla. E-mailová adresa je identifikátorem účtu a její změna může být z bezpečnostních důvodů řešena individuálně prostřednictvím podpory.</p>
<p><strong>12. Zrušení účtu.</strong> Zákazník může požádat o zrušení zákaznického účtu prostřednictvím podpory Luvia Decor. Zrušení účtu nemá samo o sobě vliv na již uzavřené smlouvy, zákonné povinnosti prodávajícího, reklamace, účetní a daňové doklady ani jiné údaje, které musí být podle právních předpisů uchovány. Po zrušení účtu mohou být příslušné údaje odstraněny nebo anonymizovány v rozsahu, v jakém jejich dalšímu uchování nebrání právní povinnost nebo oprávněný důvod.</p>
<p><strong>13. Dočasná nedostupnost.</strong> Luvia Decor může zákaznický účet nebo jeho jednotlivé funkce dočasně omezit z technických, bezpečnostních nebo provozních důvodů. Takové omezení nemá rušit zákonná práva zákazníka ani jeho již uzavřené smlouvy.</p>
<p><strong>14. Zneužití účtu.</strong> Účet nesmí být používán k podvodům, automatizovanému zneužívání systému, pokusům o neoprávněný přístup, obcházení slevových pravidel nebo jinému protiprávnímu jednání. Při důvodném podezření může Luvia Decor účet nebo jeho funkce dočasně zabezpečit a situaci ověřit. Tím nejsou dotčena zákonná práva spotřebitele.</p>
<p><strong>15. Ochrana osobních údajů.</strong> Osobní údaje spojené se zákaznickým účtem jsou zpracovávány pro účely vedení účtu, poskytování jeho funkcí, zpracování objednávek a plnění právních povinností podle příslušných právních předpisů. Podrobnosti o rozsahu, účelech, době uchování a právech zákazníka jsou uvedeny v dokumentu „Ochrana osobních údajů“.</p>
<p><strong>16. Postup při založení účtu.</strong> Zákazník zvolí „Můj Luvia“ → „Vytvořit účet“, vyplní požadované údaje, nastaví heslo a dokončí registraci. Následně se může přihlásit a doplnit adresy, oblíbené produkty, kolekce a preference. Účet není podmínkou nákupu a jeho vytvoření samo o sobě nevytváří objednávku.</p>
<p className="pt-2 text-xs text-[#8A7A6D]">Toto ustanovení doplňuje ostatní obchodní podmínky. V případě rozporu má přednost kogentní právní úprava a konkrétní individuální ujednání se zákazníkem.</p>
</div></div></section>;
