import { useEffect } from 'react';
const STATUS_OPTIONS=[['nova','Nová'],['zpracovava_se','Zpracovává se'],['zaplaceno','Zaplaceno'],['u_prepravce','U přepravce'],['odeslano','Odesláno'],['dokonceno','Dokončeno'],['zruseno','Zrušeno']] as const;
function addMissingStatusOptions(select:HTMLSelectElement){STATUS_OPTIONS.forEach(([value,label])=>{if(!Array.from(select.options).some(o=>o.value===value))select.add(new Option(label,value));});}
function isOrderStatusSelect(select:HTMLSelectElement){const values=Array.from(select.options).map(o=>o.value);return !values.includes('all')&&values.includes('nova')&&(values.includes('dokonceno')||values.includes('zruseno'));}
function ensureStatusOptions(){document.querySelectorAll<HTMLSelectElement>('#admin-dashboard-view select').forEach(select=>{if(isOrderStatusSelect(select)){addMissingStatusOptions(select);if(!select.dataset.previousStatus)select.dataset.previousStatus=select.value;}});}
function getOrderCard(select:HTMLSelectElement):HTMLElement|null{let current:HTMLElement|null=select.parentElement;while(current&&current!==document.body){const text=current.textContent||'';if(/LUV-\d{4}-\d+/i.test(text)&&current.querySelector('select'))return current;current=current.parentElement;}return select.closest<HTMLElement>('div.border');}
async function loadOrders(){const response=await fetch('/api/orders',{cache:'no-store'});if(!response.ok)throw new Error('Nepodařilo se načíst objednávky.');const data=await response.json();if(!Array.isArray(data))throw new Error('Server vrátil neplatná data objednávek.');return data;}
function setBadge(card:HTMLElement|null,text:string,success:boolean){if(!card)return;let badge=card.querySelector<HTMLElement>('[data-status-save-result]');if(!badge){badge=document.createElement('span');badge.dataset.statusSaveResult='true';badge.className='inline-flex items-center gap-1.5 ml-2 px-2.5 py-1 rounded-full text-[10px] font-bold';const select=card.querySelector('select');select?.parentElement?.appendChild(badge);}badge.textContent=text;badge.className=`inline-flex items-center gap-1.5 ml-2 px-2.5 py-1 rounded-full text-[10px] font-bold ${success?'bg-emerald-50 text-emerald-700 border border-emerald-200':'bg-rose-50 text-rose-700 border border-rose-200'}`;}
async function saveOrderStatus(select:HTMLSelectElement,status:string){const card=getOrderCard(select);const text=card?.textContent||'';const number=text.match(/LUV-\d{4}-\d+/i)?.[0]||'';const orders=await loadOrders();const order=orders.find((item:any)=>String(item?.orderNumber||'').toLowerCase()===number.toLowerCase());if(!order?.id)throw new Error('Objednávku se nepodařilo najít.');const response=await fetch(`/api/orders/${encodeURIComponent(String(order.id))}/status`,{method:'PUT',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({status})});const data=await response.json().catch(()=>null);if(!response.ok||data?.success!==true)throw new Error(data?.error||`Aktualizace selhala (${response.status}).`);let email=data?.statusEmail;if(email?.sent!==true){const fallback=await fetch('/api/order-status-email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderId:order.id,status})});const fallbackData=await fallback.json().catch(()=>null);if(fallback.ok&&fallbackData?.success===true)email=fallbackData;else if(!email?.error)email={sent:false,error:fallbackData?.error||'E-mail se nepodařilo odeslat.'};}return{order:data,email};}
function updateVisibleStatus(card:HTMLElement|null,nextStatus:string){if(!card)return;const label=STATUS_OPTIONS.find(([value])=>value===nextStatus)?.[1]||nextStatus;card.dataset.orderStatus=nextStatus;card.querySelectorAll<HTMLElement>('[data-order-status],[data-status],.order-status,.status-badge,.status').forEach(el=>{if(!(el instanceof HTMLSelectElement))el.textContent=label;});}
function handleStatusChange(event:Event){const target=event.target;if(!(target instanceof HTMLSelectElement)||!isOrderStatusSelect(target))return;event.stopImmediatePropagation();const nextStatus=target.value;const previousStatus=target.dataset.previousStatus||nextStatus;if(nextStatus===previousStatus)return;const card=getOrderCard(target);target.disabled=true;setBadge(card,'Ukládám změnu…',true);void saveOrderStatus(target,nextStatus).then(({order,email})=>{target.dataset.previousStatus=nextStatus;updateVisibleStatus(card,nextStatus);setBadge(card,email?.sent===true?'✓ Stav změněn · e-mail odeslán':'✓ Stav změněn · e-mail se nepodařilo odeslat',email?.sent===true);window.dispatchEvent(new CustomEvent('luvia-order-status-updated',{detail:{orderId:order.id,status:nextStatus,email}}));}).catch(error=>{target.value=previousStatus;target.dataset.previousStatus=previousStatus;setBadge(card,'✕ Změnu se nepodařilo uložit',false);window.alert(error instanceof Error?error.message:'Aktualizace stavu selhala.');}).finally(()=>{target.disabled=false;});}
export function OrderStatusEnhancer(){useEffect(()=>{ensureStatusOptions();document.addEventListener('change',handleStatusChange,true);const observer=new MutationObserver(ensureStatusOptions);observer.observe(document.body,{childList:true,subtree:true});return()=>{document.removeEventListener('change',handleStatusChange,true);observer.disconnect();};},[]);return null;}