import type { VercelRequest,VercelResponse } from '@vercel/node';
import { neon } from '@neondatabase/serverless';
import { Resend } from 'resend';
import { randomBytes } from 'node:crypto';
const sql=neon(process.env.DATABASE_URL||'');
const MIN_AMOUNT=200;
const SELLER_EMAIL=process.env.ORDER_NOTIFY_EMAIL||'objednavky@luvia-decor.cz';
async function ensureTable(){await sql`CREATE TABLE IF NOT EXISTS coupons (id TEXT PRIMARY KEY, code TEXT UNIQUE NOT NULL, type TEXT NOT NULL, value NUMERIC NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), note TEXT)`;await sql`ALTER TABLE coupons ADD COLUMN IF NOT EXISTS note TEXT`;await sql`ALTER TABLE coupons ADD COLUMN IF NOT EXISTS category_ids JSONB NOT NULL DEFAULT '[]'::jsonb`;await sql`ALTER TABLE coupons ADD COLUMN IF NOT EXISTS remaining_value NUMERIC`;await sql`ALTER TABLE coupons ADD COLUMN IF NOT EXISTS security_code TEXT`;await sql`UPDATE coupons SET category_ids='[]'::jsonb WHERE category_ids IS NULL`;await sql`UPDATE coupons SET remaining_value=value WHERE note='gift-voucher' AND remaining_value IS NULL`;await sql`CREATE TABLE IF NOT EXISTS gift_card_topups (id TEXT PRIMARY KEY,coupon_id TEXT NOT NULL,code TEXT NOT NULL,amount NUMERIC NOT NULL,email TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),confirmed_at TIMESTAMPTZ)`}
function send(res:VercelResponse,status:number,body:unknown){res.setHeader('Cache-Control','no-store,no-cache,must-revalidate,proxy-revalidate');res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET, POST, PUT, DELETE, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');return res.status(status).json(body)}
function parseCategoryIds(value:unknown):string[]{if(Array.isArray(value))return value.map(String).map(v=>v.trim()).filter(Boolean);if(typeof value==='string'){try{const parsed=JSON.parse(value);if(Array.isArray(parsed))return parsed.map(String).map(v=>v.trim()).filter(Boolean)}catch{}}return[]}
function row(r:any,includeSecret=false){const gift=r.note==='gift-voucher';const remaining=gift?(r.remaining_value==null?Number(r.value):Number(r.remaining_value)):Number(r.value);return{id:r.id,code:String(r.code),type:r.type,value:gift?remaining:Number(r.value),originalValue:Number(r.value),active:Boolean(r.active),createdAt:r.created_at,note:r.note||'',giftVoucher:gift,categoryIds:parseCategoryIds(r.category_ids),remainingValue:remaining,...(includeSecret&&gift&&r.security_code?{securityCode:String(r.security_code)}:{})}}
async function findGift(codeRaw:unknown){const code=String(codeRaw||'').trim().toUpperCase();if(!code)return null;const rows=await sql`SELECT id,code,type,value,active,created_at,note,category_ids,remaining_value,security_code FROM coupons WHERE UPPER(TRIM(code))=${code} AND note='gift-voucher' LIMIT 1`;return rows[0]||null}
async function validateCode(rawCode:unknown,rawSecurity:unknown){const code=String(rawCode||'').trim().toUpperCase();const security=String(rawSecurity||'').trim().toUpperCase();if(!code)return{status:400,body:{valid:false,error:'Zadejte kód dárkové karty.'}};if(!security)return{status:400,body:{valid:false,error:'Zadejte bezpečnostní kód dárkové karty.'}};const rows=await sql`SELECT id,code,type,value,active,created_at,note,category_ids,remaining_value,security_code FROM coupons WHERE UPPER(TRIM(code))=${code} AND active=TRUE LIMIT 1`;if(!rows.length)return{status:404,body:{valid:false,error:'Dárková karta nebyla nalezena nebo je neaktivní.'}};const result=row(rows[0]);if(!result.giftVoucher||!rows[0].security_code||String(rows[0].security_code).trim().toUpperCase()!==security)return{status:403,body:{valid:false,error:'Bezpečnostní kód dárkové karty není správný.'}};if(result.value<=0)return{status:400,body:{valid:false,error:'Tato dárková karta již nemá žádnou využitelnou hodnotu.'}};return{status:200,body:{valid:true,...result}}}
async function email(html:string,to:string,subject:string){const key=process.env.RESEND_API_KEY;if(!key)return false;try{const resend=new Resend(key);await resend.emails.send({from:'Luvia Decor <objednavky@luvia-decor.cz>',to,replyTo:'podpora@luvia-decor.cz',subject,html});return true}catch(e){console.warn('Gift card email failed',e);return false}}
const layout=(title:string,body:string)=>`<!doctype html><html lang="cs"><body style="margin:0;background:#f4f0eb;font-family:Arial,sans-serif;color:#302923"><div style="padding:30px 12px"><div style="max-width:620px;margin:auto;background:white;border:1px solid #e7dfd6;border-radius:20px;overflow:hidden"><div style="background:#211c18;padding:28px;text-align:center;color:#faf6f0;font-size:25px;letter-spacing:4px;font-weight:700">LUVIA DECOR</div><div style="padding:30px"><div style="font-size:11px;letter-spacing:2px;text-transform:uppercase;color:#b08f65;font-weight:700">${title}</div>${body}</div><div style="padding:20px;text-align:center;background:#faf8f5;color:#756b63;font-size:12px">Luvia Decor · U Rejdiště 3732/15, 767 01 Kroměříž · IČO 29905061</div></div></div></body></html>`;
async function handler(req:VercelRequest,res:VercelResponse){if(req.method==='OPTIONS')return send(res,204,{});try{await ensureTable();const action=String(req.query.action||'');const id=typeof req.query.id==='string'?req.query.id:undefined;
 if(action==='validate'&&(req.method==='GET'||req.method==='POST')){const rawCode=req.method==='GET'?req.query.code:req.body?.code;const rawSecurity=req.method==='GET'?req.query.securityCode:req.body?.securityCode;const result=await validateCode(rawCode,rawSecurity);return send(res,result.status,result.body)}
 if(action==='topup-request'&&req.method==='POST'){const code=String(req.body?.code||'').trim().toUpperCase();const amount=Number(req.body?.amount);const emailAddress=String(req.body?.email||'').trim().toLowerCase();if(!emailAddress||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(emailAddress))return send(res,400,{error:'Zadejte platný e-mail.'});if(!Number.isFinite(amount)||amount<MIN_AMOUNT)return send(res,400,{error:`Dobití musí být alespoň ${MIN_AMOUNT} Kč.`});const card=await findGift(code);if(!card||!card.active)return send(res,404,{error:'Dárková karta nebyla nalezena nebo je neaktivní.'});const topupId=`topup-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;await sql`INSERT INTO gift_card_topups (id,coupon_id,code,amount,email) VALUES (${topupId},${card.id},${card.code},${amount},${emailAddress})`;await email(layout('Nová žádost o dobití',`<h1 style="font-size:24px">Dobití dárkové karty</h1><p>Kód: <strong>${card.code}</strong><br>Částka: <strong>${amount.toLocaleString('cs-CZ',{minimumFractionDigits:2,maximumFractionDigits:2})} Kč</strong><br>E-mail zákazníka: <strong>${emailAddress}</strong><br>ID žádosti: <strong>${topupId}</strong></p><p>Částka se nepřipisuje automaticky. Administrace ji připíše až po ověření zaplacení.</p>`),SELLER_EMAIL,`DOBITÍ DÁRKOVÉ KARTY · ${card.code} · ${amount} Kč`);return send(res,201,{success:true,id:topupId,code:card.code,amount})}
 if(action==='topup-requests'&&req.method==='GET'){const rows=await sql`SELECT id,coupon_id,code,amount,email,status,created_at,confirmed_at FROM gift_card_topups ORDER BY created_at DESC`;return send(res,200,rows)}
 if(action==='confirm-topup'&&req.method==='POST'){const topupId=String(req.body?.id||'');if(!topupId)return send(res,400,{error:'Chybí ID žádosti.'});const result=await sql`UPDATE gift_card_topups SET status='confirmed',confirmed_at=NOW() WHERE id=${topupId} AND status='pending' RETURNING id,coupon_id,code,amount,email`;if(!result.length)return send(res,409,{error:'Žádost již byla vyřízena nebo neexistuje.'});const t=result[0];const updated=await sql`UPDATE coupons SET remaining_value=COALESCE(remaining_value,value)+${Number(t.amount)},active=TRUE WHERE id=${t.coupon_id} AND note='gift-voucher' RETURNING code,remaining_value`;if(!updated.length){await sql`UPDATE gift_card_topups SET status='pending',confirmed_at=NULL WHERE id=${topupId}`;return send(res,404,{error:'Dárková karta nebyla nalezena.'})}return send(res,200,{success:true,code:t.code,remainingValue:Number(updated[0].remaining_value)})}
 if(action==='cancel-topup'&&req.method==='POST'){const topupId=String(req.body?.id||'');const r=await sql`UPDATE gift_card_topups SET status='cancelled' WHERE id=${topupId} AND status='pending' RETURNING id`;if(!r.length)return send(res,404,{error:'Žádost nebyla nalezena nebo již byla vyřízena.'});return send(res,200,{success:true})}
 if(req.method==='GET'){const rows=await sql`SELECT id,code,type,value,active,created_at,note,category_ids,remaining_value FROM coupons ORDER BY created_at DESC`;return send(res,200,rows.map(r=>row(r)))}
 if(req.method==='POST'){const code=String(req.body?.code||'').replace(/\s+/g,' ').trim().toUpperCase();const type=req.body?.type==='fixed'?'fixed':'percent';const value=Number(req.body?.value)||0;const note=String(req.body?.note||'');const categoryIds=parseCategoryIds(req.body?.categoryIds);const voucher=note==='gift-voucher';if(!code||value<=0)return send(res,400,{error:'Zadejte kód a kladnou hodnotu.'});if(voucher&&value<MIN_AMOUNT)return send(res,400,{error:`Dárková karta musí mít alespoň ${MIN_AMOUNT} Kč.`});if(type==='percent'&&value>100)return send(res,400,{error:'Procentní sleva může být nejvýše 100 %.'});const idValue=`cup-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;const securityCode=voucher?`LUVIA-SEC-${randomBytes(8).toString('hex').toUpperCase()}`:null;const rows=await sql`INSERT INTO coupons (id,code,type,value,active,note,category_ids,remaining_value,security_code) VALUES (${idValue},${code},${type},${value},${req.body?.active!==false},${note},${JSON.stringify(categoryIds)}::jsonb,${voucher?value:null},${securityCode}) ON CONFLICT(code) DO UPDATE SET type=EXCLUDED.type,value=EXCLUDED.value,active=EXCLUDED.active,note=EXCLUDED.note,category_ids=EXCLUDED.category_ids,remaining_value=CASE WHEN EXCLUDED.note='gift-voucher' THEN COALESCE(coupons.remaining_value,EXCLUDED.value) ELSE coupons.remaining_value END,security_code=CASE WHEN EXCLUDED.note='gift-voucher' THEN COALESCE(coupons.security_code,EXCLUDED.security_code) ELSE coupons.security_code END RETURNING id,code,type,value,active,created_at,note,category_ids,remaining_value,security_code`;return send(res,201,row(rows[0],voucher))}
 if(!id)return send(res,400,{error:'Chybí ID slevového kódu.'});
 if(req.method==='PUT'){const fields:any={};if(typeof req.body?.active==='boolean')fields.active=req.body.active;if(req.body?.remainingValue!=null){const n=Number(req.body.remainingValue);if(!Number.isFinite(n)||n<0)return send(res,400,{error:'Neplatný zůstatek.'});fields.remainingValue=n}if(!Object.keys(fields).length)return send(res,400,{error:'Chybí data k aktualizaci.'});const rows=await sql`UPDATE coupons SET active=COALESCE(${fields.active??null},active),remaining_value=CASE WHEN ${fields.remainingValue??null} IS NULL THEN remaining_value ELSE ${fields.remainingValue??null} END WHERE id=${id} RETURNING id,code,type,value,active,created_at,note,category_ids,remaining_value`;if(!rows.length)return send(res,404,{error:'Slevový kód nenalezen.'});return send(res,200,row(rows[0]))}
 if(req.method==='DELETE'){await sql`DELETE FROM coupons WHERE id=${id}`;return send(res,200,{success:true})}
 return send(res,405,{error:'Metoda není podporovaná.'})
 }catch(error){console.error('Coupons API error:',error);return send(res,500,{error:error instanceof Error?error.message:'Slevové kódy se nepodařilo zpracovat.'})}}
export default handler;